### ISSUE TITLE
Code Analysis: Goreturns 404

### ISSUE THREAD

**Issue by xmattstrongx** [avelino/awesome-go#1012]
The goreturns link takes you to a 404 here:
https://sourcegraph.com/sqs/goreturns 

Not sure but you might want this links instead?
https://sourcegraph.com/github.com/sqs/goreturns

**Comment by xmattstrongx** [comment]
update it myself with the sourcegraph link and submitted a PR https://github.com/avelino/awesome-go/pull/1013

Not sure if sourcegraph or github was preferred??

**Comment by shurcooL** [comment]
I think that url is okay, thanks for fixing the 404! /cc @sqs

**Comment by kirillDanshin** [comment]
@shurcooL I believe it's a sourcegraph bug. they forgot to make a redirector.
thanks again @xmattstrongx
