### ISSUE TITLE
Gotty: Add Share your terminal as a web application

### ISSUE THREAD

**Issue by zyfdegh** [avelino/awesome-go#1092]
Amazing project! Highly recommended! 

[https://github.com/yudai/gotty](https://github.com/yudai/gotty)

It can turn any command line application to web application!

**Comment by shurcooL** [comment]
Thanks for letting us know @zyfdegh. If you'd like to add it to awesome-go list, please create a PR and follow the steps in the [template](https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md). Thanks!
