### ISSUE TITLE
Add godoctor refactoring engine

### ISSUE THREAD

**Issue by cmpis** [avelino/awesome-go#1105]
https://github.com/godoctor/godoctor

> The Go Doctor is an automated refactoring tool for the Go programming language. It currently supports: 
>
> Rename
> Extract Function
> Toggle var ⇔ :=
> Add Godoc stubs
> 
> Try out the Go Doctor using the online demo to the left. Then, install it on your machine. There is a Vim plug-in for the Go Doctor, or it can be run directly from the command line.

**Comment by shurcooL** [comment]
Thanks @cmpis. If you'd like to add it to awesome-go list, please create a PR and follow the steps in the [template](https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md). Thanks!
