### ISSUE TITLE
I add robotgo,but Some checks were not successful

### ISSUE THREAD

**Issue by vCaesar** [avelino/awesome-go#1124]
I add robotgo,but Some checks were not successful;but like godoc.org is Instability in this network;Please add [robotgo](https://github.com/go-vgo/robotgo),doc in the github,[doc](https://github.com/go-vgo/robotgo/blob/master/doc.md),thank you;https://github.com/avelino/awesome-go/pull/1123

**Comment by kirillDanshin** [comment]
rebase it.
