### ISSUE TITLE
Dead link/project: gogenerate

### ISSUE THREAD

**Issue by zet4** [avelino/awesome-go#1181]
While browsing the list I found https://github.com/arschles/gogenerate to be a dead link (in Testing)

**Comment by shurcooL** [comment]
I can confirm it's 404.

@arschles, what's the status of that repository? Has it moved/been renamed? Or is it gone and we should remove the link to it?

**Comment by avelino** [comment]
I couldn't find anything saying it was renamed (and no keeping fork)

**Comment by arschles** [comment]
Yup, you're right - that project is dead. I didn't have time to keep it going. Sorry I forgot to update it.

Side question: is this list alive again?

**Comment by avelino** [comment]
@arschles awesome-go has always been alive, we need more employees to keep the list (most up to date as possible)

**Comment by avelino** [comment]
@zet4 thank you!

**Comment by arschles** [comment]
@zet4 good to know, for some reason I thought it had gone dormant, so sorry about that!

I will try to come back often and help out with keeping it up to date!
