### ISSUE TITLE
Update tests to show correct order.

### ISSUE THREAD

**Issue by zet4** [avelino/awesome-go#1217]
So recently I copied avelino/awesome-go structure for my own community listing for a service.
While dealing with helping people add new items because of the forced alpha sort I came up with a quick fix for it which can be seen in my [repo_test.go](https://github.com/beautiful-discord-community/resources/blob/master/repo_test.go),  line [95](https://github.com/beautiful-discord-community/resources/blob/master/repo_test.go#L95) in particular, basically it logs the correct order if there's an error, I also ported my test to 1.7 (I use t.Run in mine).

**Comment by shurcooL** [comment]
That sounds like a useful thing. Are you interested in making a PR for it?

**Comment by zet4** [comment]
If you don't mind me updating travis to 1.7 and rewriting it to use testing instead of log then sure

**Comment by shurcooL** [comment]
I don't see why not. Go 1.7 is the current stable release of Go.

**Comment by zet4** [comment]
I think you can see that in my PR but yes you do use log in your current testing.
