### ISSUE TITLE
integration with var.ci or something like it

### ISSUE THREAD

**Issue by kamilsk** [avelino/awesome-go#1260]
I see that sometimes people do not provide correct description to their pull requests. So, maybe it is better to integrate with some services look like var.ci ?

You can see it in action in similar project https://github.com/ziadoz/awesome-php/pull/755.

What do you think?

**Comment by shurcooL** [comment]
Sounds like a good idea, since this can indeed be automated.

Unless there are objections, someone motivated can work on implementing this.

**Comment by appleboy** [comment]
Sounds Good.

**Comment by felipeweb** [comment]
Sounds good

**Comment by kirillDanshin** [comment]
I think we should create a SoundsGoodBot 🤔
