### ISSUE TITLE
Within each category have sub-categories: "Native" & "Non-native"

### ISSUE THREAD

**Issue by gnewton** [avelino/awesome-go#1289]
Native libraries are important (to many), so being able to quickly find the native vs. non-native would be useful. Having to search through is a pain. 

Or, perhaps have a symbol or text colour that makes it easy to find native libs?

**Comment by refaelsh** [comment]
+1

**Comment by avelino** [comment]
This link lists all the native packages, doesn't that solve?
https://golang.org/pkg/

We can insert this link in [websites topic](https://github.com/avelino/awesome-go#websites) or [header](https://github.com/avelino/awesome-go#awesome-go---) (on README), you see how a solution?

#sorrydelayonreply

**Comment by cassiobotaro** [comment]
what means a native package?

**Comment by avelino** [comment]
Close by lack of interaction
