### ISSUE TITLE
"awesome-go" tags

### ISSUE THREAD

**Issue by kirillDanshin** [avelino/awesome-go#1309]
I propose to start an official `awesome-go` tag, so folks can search awesome go libs and see that they was reviewed by our list maintaining team, and a tags to search who exactly in our team approved the lib. For example, [go-isatty](github.com/mattn/go-isatty) could have [awesome-go] and [kirilldanshin] tags, [go-sciter](https://github.com/sciter-sdk/go-sciter) could have [awesome-go] and [appleboy] tags etc.

**Comment by shurcooL** [comment]
I'm not sure what you mean by "tags", can you please elaborate?

**Comment by kirillDanshin** [comment]
@shurcooL GitHub topics. e.g., you can search `topic:awesome-go` to search for `awesome-go` topic (a.k.a. tag)

**Comment by appleboy** [comment]
I am ok.

**Comment by avelino** [comment]
ok

**Comment by joeybloggs** [comment]
My only question is are there really any benefits to adding the name of the approver?

I'm on board with the awesome-go tag.

**Comment by kirillDanshin** [comment]
@joeybloggs it's pretty useful for our dear folks. for example, our russian community frequently ask question like "is there any libs to do *X* that tested by *Y*". here *X* is anything you can do with Go, and *Y* mainly is one of @avelino, @shurcooL, @appleboy or my nickname 😄
so I think, first of all, we should have awesome-go tag, and I really want to give our folks ability to just search for *X*, filter out by awesome-go and *maintainer_nickname* tags and find some really awesome for *X*

**Comment by joeybloggs** [comment]
That makes perfect sense @kirillDanshin :+1: I didn't realise people would or are searching by tester/approver

**Comment by dukex** [comment]
Nice idea @kirillDanshin !

**Comment by matrixik** [comment]
Good idea even that I don't think my reviews was of enough quality to tag some repos with my name.

**Comment by avelino** [comment]
Would we put this tag after accepting the PR? Generating a new commit?
It would be ideal to be automatic, does anyone have any idea how to do it?

**Comment by kirillDanshin** [comment]
I can write a bot that will open an issue for merged libraries

**Comment by avelino** [comment]
Very nice @kirillDanshin , send PR pls
After entering the master I put it to run on the same server as the `awesome-go.com`
