### ISSUE TITLE
"stats and metrics" category?

### ISSUE THREAD

**Issue by cactus** [avelino/awesome-go#1374]
Is a "stats and metrics" category desired?
Could be useful for things like:
* [rcrowley/go-metrics](https://github.com/rcrowley/go-metrics) - Go port of Coda Hale's Metrics library
* [armon/go-metrics](https://github.com/armon/go-metrics) - A Golang library for exporting performance and runtime metrics to external metrics systems (i.e. statsite, statsd)
* [cactus/go-statsd-client](https://github.com/cactus/go-statsd-client) - statsd client for Go

and others, I am sure.

**Comment by avelino** [comment]
@cactus you send PR pls?

**Comment by cactus** [comment]
@avelino ok. PR opened.

**Comment by jtemporal** [comment]
#1605 was closed if anyone wants to address this issue feel free to do it. :smile:

**Comment by cactus** [comment]
I tried, but it was rejected because projects *already linked to in the file* (just moved to the new category) failed some lint tests. Good luck to anyone with more time on their hands to pester upstream repositories!

**Comment by jtemporal** [comment]
Hi @cactus unfortunately the packages need meet the quality standards on our contributing guide. That helps us keep a curated high level listing of packages. That's one of the things that make them awesome :wink:

**Comment by ceriath** [comment]
Apparently there is no real need for this right now, so i am closing this issue.

**Comment by cactus** [comment]
@jtemporal You realize it was a link that /already existed/ in the document, that was just /moved/, right?
It just so happened that moving it made it appear in the diff, and thus the bot had a chance to re-check it.

If such strict adherence is a requirement, then my recommendation is to recheck all repos periodically to avoid negative drift.
