### ISSUE TITLE
Stats for projects

### ISSUE THREAD

**Issue by zerkms** [avelino/awesome-go#1391]
Hi :-)

I just released a pre-alpha version of a Go tool that adds projects' stats directly into the awesome list, so that it was easier to choose among the most popular libs/projects

I created it because sometimes when you need to choose a library - there are 20 alternatives, but in most cases choosing among the most popular one (since they usually are the most supported ones or with the most features) is the easiest strategy.

That's how the `Audio/Music` could look like with that:

![sample](https://raw.githubusercontent.com/zerkms/awesome-stats/master/docs/after.png)

What do you think of it? :-)

**Comment by avelino** [comment]
#1213
