### ISSUE TITLE
Go:Generate

### ISSUE THREAD

**Issue by Konstantin8105** [avelino/awesome-go#1436]
Could you create in https://github.com/avelino/awesome-go a new part for GoTools - Go:Generate and add a few projects:
https://github.com/cheekybits/genny
https://github.com/vektra/mockery
https://github.com/maxbrunsfeld/counterfeiter
https://github.com/yudppp/json_snake_case
https://github.com/alvaroloes/enumer
https://github.com/opennota/re2dfa

and many other :)
Have fun.

**Comment by Konstantin8105** [comment]
https://github.com/sasha-s/go-inline#generating-derived-code

**Comment by avelino** [comment]
you send PR pls?

**Comment by Konstantin8105** [comment]
Awesome, but tomorrow. :)

**Comment by Konstantin8105** [comment]
Is that issue closed
