### ISSUE TITLE
Add a new rule to the guideline

### ISSUE THREAD

**Issue by PotHix** [avelino/awesome-go#1458]
The project currently has 163 pull requests waiting for approval. Many of them are waiting for the author, instead of waiting for approvers.

I propose to add a new condition to all PRs: If the pull request was reviewed and is waiting for the author interaction for more than 5 days, it will be closed.

A project that is just text and has more than 150 opened PRs is weird for those who don't know it, this change will help with that.

**Comment by joeybloggs** [comment]
I'd say a time limit is a good idea, but 5 days may be too short a window, most people are pretty busy.

eg. Person finds time on Sunday to make a PR that requires some changes that he doesn't see till Monday but is busy with work, kids, open source projects etc... The PR would get closed before he may even find time to make changes.

I'd say at least 8 days to be fair, maybe longer, thoughts?

**Comment by PotHix** [comment]
LGTM

**Comment by felipeweb** [comment]
LGTM

**Comment by avelino** [comment]
@PotHix send PR upgrade contribute file and PR template pls

**Comment by appleboy** [comment]
LGTM @PotHix Please send the PR.

**Comment by matrixik** [comment]
LGTM with more days than 5. 8-10 looks fine, but no more than 14.

**Comment by dukex** [comment]
LGTM, thanks @PotHix

**Comment by kirillDanshin** [comment]
LGTM, and I agree with @matrixik
