### ISSUE TITLE
wanna add foxmutex repo

### ISSUE THREAD

**Issue by cokeboL** [avelino/awesome-go#1541]
foxmutex is a lib which helps to debug deadlock, it will log out of relative code's stacks info.
I want to make a pull request for foxmutex repo: [https://github.com/naivefox/foxmutex](https://github.com/naivefox/foxmutex)
 I think it should be under 'Debug', but there isn't a ‘Debug' categorie.
And I don't use coverage service, is it a must for pull request?

**Comment by avelino** [comment]
send PR pls
