### ISSUE TITLE
idea: make https://awesome-go.com/ a more sophisticated server than one index page

### ISSUE THREAD

**Issue by c0b** [avelino/awesome-go#1548]
from JavaScript background world here, the https://bestof.js.org/ serves as a curated list of all awesome JavaScript projects, but this site does more things than current https://awesome-go.com/ is only one static index page

1. project page like (https://bestof.js.org/projects/bootstrap) has imported README from the project
2. can list all projects order by popularity or by trending,
     like https://bestof.js.org/projects/trending/this-week list all js projects which got the most incremental number of stars in the past week; I personally also feel the trending is a good way to recognize the old out-of-maintenance projects, I've seen many curated awesome list got out-dated as well, or their contents becoming containing many out-dated information, it's hard to invalidate
3. list projects by tags, like https://bestof.js.org/tags/react is showing only react related tags
4. Hall of Fame https://bestof.js.org/hof list the most active ones who contributed the most or best quality javascript code, all based on each individual's github account
5. make annual reports on which projects was the most popular, and for each domain,  https://risingstars2016.js.org/ for a longer term this serves best guiding

all these together look like a big project, more of a big data analysis project based on available public github API call; but it might be finally worth it, and beyond all available bestof.js.org features, we can also think about new innovative ideas, like #1454 can be based on meetup API https://www.meetup.com/topics/go/

**Comment by avelino** [comment]
Optimal Ideai, automatically extracting from markdown (maintaining a single information base).
Do you implement it?

**Comment by XELAJ** [comment]
it would be cool to make export *.md file, cause you can get more features like top of packages, pre-moderating (from community) cool things etc. but it is just imho, don't critiсize it :thinking:
