### ISSUE TITLE
add application category: internet application

### ISSUE THREAD

**Issue by c0b** [avelino/awesome-go#1550]
the Lantern project is a great tool for people to circumvent internet censorship system, for those who live in China, Iran, Cuba, and anywhere has large scale internet censorship, the official introduction from https://getlantern.org
:          Fast, reliable and secure access to the open internet

1. https://github.com/getlantern/lantern (written in Go)
2. https://getlantern.org/en_US/

**Comment by avelino** [comment]
read pls https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines
`At least 3 items are needed to create a new category.`
