### ISSUE TITLE
Add sift search tool to this index please.

### ISSUE THREAD

**Issue by ipstone** [avelino/awesome-go#1588]
This is a really cool tool: https://github.com/svent/sift

**Comment by cassiobotaro** [comment]
@ipstone feel free to open a PR

**Comment by EyesBear** [comment]
@avelino That repo doesn't have godoc, goreportcard or tests.
Their doc is located here: https://sift-tool.org/docs.
Is it still ok to add it?

**Comment by cassiobotaro** [comment]
yep

**Comment by cassiobotaro** [comment]
yes
