### ISSUE TITLE
chat channel, gitter or gopher slack

### ISSUE THREAD

**Issue by avelino** [avelino/awesome-go#1666]
Today we use `Gitter` as a channel for instant communication.

Which channel do you prefer?
- gitter - https://gitter.im/avelino/awesome-go
- gopher slack (required subscription, unfortunately) - http://gophers.slack.com/messages/awesome-go

**Comment by crgimenes** [comment]
gopher slack for me

**Comment by felipeweb** [comment]
i really prefer slack

**Comment by appleboy** [comment]
Create new channel in https://gophers.slack.com

**Comment by felipeweb** [comment]
http://gophers.slack.com/messages/awesome-go

**Comment by avelino** [comment]
@felipeweb exist [#awesome](http://gophers.slack.com/messages/awesome) we're inside the slack go, it doesn't make sense to put `-go` in the end (suffix), pls close channel `#awesome-go`

**Comment by felipeweb** [comment]
I do not have permission to delete channels even created by me
Em seg, 6 de nov de 2017 às 13:02, Avelino <notifications@github.com>
escreveu:

**Comment by matrixik** [comment]
From this two I have no preference, other out of this two I prefer discordapp.com

**Comment by appleboy** [comment]
I vote discordapp.com +1

**Comment by kirillDanshin** [comment]
p.s. @avelino https://awesome-go.com/ is down, check out ASAP plz

**Comment by avelino** [comment]
My opinion: I think I better go to where the community has, today `slack`
About discord: We would have to create a new community, convince people to use discord

All agree to `migrate to slack`?
