### ISSUE TITLE
Gopher resources category?

### ISSUE THREAD

**Issue by uLan08** [avelino/awesome-go#1695]
How about a list of repos that has gopher resources? I have a few in mind.

**Comment by avelino** [comment]
What do you mean by "gopher resources", sent example

**Comment by uLan08** [comment]
What I mean by gopher resources is repos or projects in where you can get images, vectors, gifs, svgs, etc. of the go gopher mascot. Here are some that I have seen.

https://github.com/ashleymcnamara/gophers
https://github.com/egonelbre/gophers
https://github.com/golang-samples/gopher-vector
https://github.com/shalakhin/gophericons

**Comment by avelino** [comment]
@uLan08 you send PR?

**Comment by uLan08** [comment]
@avelino Yes, will do.

**Comment by appleboy** [comment]
fixed via #1716
