### ISSUE TITLE
slack badge doesn't render on https://awesome-go.com/

### ISSUE THREAD

**Issue by ldemailly** [avelino/awesome-go#1751]
while it works fine on github, on https://awesome-go.com/ I get
![screen shot 2018-01-04 at 12 02 56 pm](https://user-images.githubusercontent.com/3664595/34581994-4aab0cc2-f147-11e7-9d8d-4ec7816140d9.png)

and
https://s3.eu-central-1.amazonaws.com/ngtuna/join-us-on-slack.png
```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>ngtuna</BucketName>
<RequestId>D9C179B337DF080A</RequestId>
<HostId>
VIGLyyt6MfPk96+nnlHg/GpW53ZmG9j9JO5L2NPZoBcIe8vADx/701yaEJso8mOpRozeHmXNdGM=
</HostId>
</Error>
```

**Comment by jtemporal** [comment]
View from firefox 57.0.1
![screenshot from 2018-01-31 12 05 27](https://user-images.githubusercontent.com/6595551/35627115-0cef161a-067f-11e8-925e-30c06ae1f5e0.png)

**Comment by ldemailly** [comment]
![screen shot 2018-01-31 at 12 55 25 pm](https://user-images.githubusercontent.com/3664595/35647006-0c542d92-0686-11e8-86da-d8d8be9ca6ba.png)
works now ! thanks !

**Comment by njncalub** [comment]
It's not showing again on both the readme file and [awesome-go.com](https://awesome-go.com/). Already did the following as suggested by the [github help pages](https://help.github.com/articles/about-anonymized-image-urls/):

```bash
curl -X PURGE https://camo.githubusercontent.com/984828c0b020357921853f59eaaa65aaee755542/68747470733a2f2f73332e65752d63656e7472616c2d312e616d617a6f6e6177732e636f6d2f6e6774756e612f6a6f696e2d75732d6f6e2d736c61636b2e706e67
```

Maybe we can try using [shields.io](https://shields.io) badges?

```
https://img.shields.io/badge/join-us%20on%20slack-gray.svg?longCache=true&logo=slack&colorB=red
```

[![Slack Widget](https://img.shields.io/badge/join-us%20on%20slack-gray.svg?longCache=true&logo=slack&colorB=red)](http://gophers.slack.com/messages/awesome)

**Comment by cassiobotaro** [comment]
@njncalub can you send a PR?

**Comment by njncalub** [comment]
Hi @cassiobotaro, I've added a PR at #2190.

**Comment by paulwaldmann** [comment]
The link "http://gophers.slack.com/messages/awesome-go" doesn't work. Any solution to join the Slack channel?
