### ISSUE TITLE
remove c6 since it's neither properly documentated nor working

### ISSUE THREAD

**Issue by hashworks** [avelino/awesome-go#1798]
I recently tried out [c6](https://github.com/c9s/c6), which describes itself as a "sass-compatible compiler". It's under development since May 2015, and has 916 commits, however 896 of those are from 2015 and only 20 happened in Aug 2017. Since then, nothing happened. Nearly every issue is from c9s himself, two issues from other people are asking about how to use this – normal when there is nearly no documentation. I had to dive into the tests - which provide only 47% coverage - to get any idea about how to implement it in my projects, however I had to give up at some point. There is a cmd tool, which literally does nothing. When asked c9s stated that it's ["not implemented yet"](https://github.com/c9s/c6/issues/82).

I have no idea how it got on this list, or how it got 391 stars. Probably got hyped sometime in 2015. I would recommend to remove this ~~piece of garbage~~ incomplete project until c9s gives this a makeover.

**Comment by avelino** [comment]
@c9s can we help your package in some way?

**Comment by ceriath** [comment]
since #2217 got merged, i am closing this issue
