### ISSUE TITLE
multi language

### ISSUE THREAD

**Issue by LuigiBaute** [avelino/awesome-go#1808]
Hello, I'm interested in contributing to this project by offering a translation to the  readme.md file, let me know if interested. the translation would be made to Spanish which is my native language.

**Comment by avelino** [comment]
@LuigiBaute I like the idea, but it would give a job to keep.

New PR we would have to make translation to other languages (the person who is sending PR may not dominate the Spanish or other languages we may have), how did you imagine this workflow?

**Comment by avelino** [comment]
Closing the issue for lack of interactivity.
@LuigiBaute failed to propose a solution
