### ISSUE TITLE
Update not showing on awesome-go.com

### ISSUE THREAD

**Issue by cuotos** [avelino/awesome-go#1903]
Is there a process I have missed to update awesome-go to match the files in the git repo? 

I added a meetup to the list, and noticed a few other PRs that don't show on a-g.com

**Comment by mnzt** [comment]
I've noticed the awesome-go website has gotten quite out of sync with the README in the repo, too.

**Comment by MobliMic** [comment]
It doesn't look like it's using GitHub pages anymore?

https://github.com/avelino/awesome-go/blob/gh-pages/index.html

Looking at this file vs the source of awesome-go.com the js file referencing the readme from the GitHub API (https://api.github.com/repos/avelino/awesome-go/git/trees/HEAD) is not called which makes me think it's being hosted elsewhere now and requires updating by the maintainer.

Unless I'm missing some trickery?

**Comment by ceriath** [comment]
@avelino what's going to happen with the site? Maybe it would be best to just redirect the domain to the repository?

**Comment by avelino** [comment]
check update now pls

**Comment by ceriath** [comment]
it's up to date now.
