### ISSUE TITLE
add grapeSQLI is easy to use Sql Inject & XSS Parser.For golang

### ISSUE THREAD

**Issue by koangel** [avelino/awesome-go#1962]
grapeSQLI
grapeSQLI is easy to use Sql Inject & XSS Parser.For pure go (like libinjection)

grapeSQLI use libinjection fingerprint data and search mode.

libinjection is great and perfect library,so we just translate related code to golang. but we optimize the code for golang.

grapeSQLI is pure go library.

**Comment by avelino** [comment]
send PR, before read: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md
