### ISSUE TITLE
Remove requirement to document implementations of official GO packages

### ISSUE THREAD

**Issue by plandem** [avelino/awesome-go#2024]
#2013

Do you really think that this is somehow related to quality of code or documentation?

What the reason to require document implementation of standard interfaces? E.g.:
```
MarshalXMLAttr
UnmarshalXMLAttr
```

From my point of view, It's just faking/cheating system and has nothing about quality of code or documentation. 

P.S.: I can give you bunch of packages from **awesome-go** list that don't even have link to http://goreportcard.com, but the same time you are strict on new packages about such things like comments for MarshalXMLAttr or UnmarshalXMLAttr.

**Comment by kirillDanshin** [comment]
@plandem sorry, but no, it's not what we're going to do. this is basic golint rules, if you want to add some exceptions - please create issue in the golint repo

**Comment by kirillDanshin** [comment]
UPD: @plandem see #2036

**Comment by plandem** [comment]
So it's fine to have packages without http://goreportcard.com at all, but for new packages you are asking to comment standard implementation?!

**Comment by plandem** [comment]
ok, got you

**Comment by shanegammell47-dot** [comment]
Thanks
