### ISSUE TITLE
Review existing packages and remove low-quality packages

### ISSUE THREAD

**Issue by kirillDanshin** [avelino/awesome-go#2036]
we should do a full review of all packages in the list to check if all packages are pass our guidelines.

**Comment by ninedraft** [comment]
Remove or refine [blas](https://github.com/ziutek/blas) repo.
No docs, no examples

**Comment by ryukinix** [comment]
Duplication of #1446?

**Comment by avelino** [comment]
> Duplication of #1446?

@ryanleary nop, this issue is so that we can review all the projects continued in the README, some project.

It would be interesting to have software that helps us to do this automatic review, I will open a issue to evolve this matter: https://github.com/avelino/awesome-go/issues/2649
