### ISSUE TITLE
Add Aaron-JM/GoHook

### ISSUE THREAD

**Issue by Aaron-JM** [avelino/awesome-go#2070]
_[GoHook](https://github.com/Aaron-JM/GoHook) is a simple library for creating discord Webhooks. It currently meets all the guidelines and will continually be improved._

**Comment by avelino** [comment]
Send pr pls

**Comment by ceriath** [comment]
This does not have any tests and seems to be still in development with open TODOs.

@Aaron-JM Feel free to submit it a PR after you finished the library :)
