### ISSUE TITLE
PR for new section "Go 2"?

### ISSUE THREAD

**Issue by networkimprov** [avelino/awesome-go#2103]
Would you accept a pull request for a new section of Go 2 links? e.g.

https://go.googlesource.com/proposal/+/master/design/go2draft.md

**Comment by kirillDanshin** [comment]
I think we can accept a PR with a section related to Go2, but we still require more than three links in the proposed category to be added.

**Comment by networkimprov** [comment]
There is a good-size number of Go 2 proposals on the issue tracker which have received broad attention, and there are posts on the feedback wikis for both generics and error handling that should be considered. Would all that be welcome/sufficient for a new category?

**Comment by ceriath** [comment]
I am not entirely sure if adding this would help out anyone. There are better places to get information about Go 2 in its current state. IMO we should wait until it's in a more finished state or a beta build or something is available.

**Comment by networkimprov** [comment]
Go 2 is not a product; please see
https://blog.golang.org/go2-here-we-come
https://github.com/golang/go/issues/29934

**Comment by ceriath** [comment]
Yes, my bad. I think we should accept a PR then, however, the three link rule still applies as mentioned already
