### ISSUE TITLE
PDF section

### ISSUE THREAD

**Issue by hhrutter** [avelino/awesome-go#2105]
Hi!

I would like to register [pdfcpu](https://github.com/hhrutter/pdfcpu) (a PDF processor) with awesome-go 
but I just can't find a category that may be a good fit.

Projects that end up under _Miscellaneous_ or _Utilities_ are hard to find and gain less visibility.
Is there any chance to create a _PDF_ category for PDF related projects?

Thank you.

**Comment by avelino** [comment]
To create a new category must have (at least) 3 packages. If I have not need to sort in another similar topic (related).

Do you send PR?

**Comment by avelino** [comment]
To me, it looks like *sub category* of **files**, sound good?

**Comment by hhrutter** [comment]
Thanks so much for accepting my project 💚
