### ISSUE TITLE
Some info

### ISSUE THREAD

**Issue by greatGregLiu** [avelino/awesome-go#2127]
a Physically Based Renderer (PBR) in Go:  https://github.com/hunterloftis/pbr

NanoGUI is a a minimalistic cross-platform widget library for OpenGL: https://github.com/shibukawa/nanogui-go

**Comment by ceriath** [comment]
Please send a PR!

**Comment by ceriath** [comment]
@greatGregLiu Feel free to submit a PR after fixing https://goreportcard.com/report/github.com/hunterloftis/pbr#gofmt :)
