### ISSUE TITLE
Add github.com/rkoesters/xdg

### ISSUE THREAD

**Issue by rkoesters** [avelino/awesome-go#2186]
https://github.com/rkoesters/xdg

I am not sure what section this would go in, maybe Configuration or Miscellaneous.

This differences between this and `github.com/OpenPeeDeeP/xdg` is that `github.com/OpenPeeDeeP/xdg` only implements the base directory standard (implemented by `github.com/rkoesters/xdg/basedir`) whereas `github.com/rkoesters/xdg` also implements:

* xdg-user-dirs (`github.com/rkoesters/xdg/userdirs`)
* xdg's trash spec (`github.com/rkoesters/xdg/trash`)
* xdg's desktop file spec with localization support (`github.com/rkoesters/xdg/desktop`)
* xdg-open (`github.com/rkoesters/xdg`)

(I am not suggesting replacing `github.com/OpenPeeDeeP/xdg`, just explaining how they are not duplicates of each other)

**Comment by avelino** [comment]
Send pr pls

**Comment by rkoesters** [comment]
Created pr https://github.com/avelino/awesome-go/pull/2227

**Comment by rkoesters** [comment]
Fixed by b2eb02979f78bf64c4cefcb055e7c3d0eb61011e
