### ISSUE TITLE
Add soar  (SQL Optimizer And Rewriter)  

### ISSUE THREAD

**Issue by liipx** [avelino/awesome-go#2195]
soar   which is a tool for optimizing SQL query and also have ability to rewrite queries.   Open source by XiaoMi AI&Cloud DBA Team.

> https://github.com/XiaoMi/soar

Now only give chinese language suggest, english version is in plan.

**Comment by avelino** [comment]
Send pr pls

**Comment by ceriath** [comment]
@liipx  Tests seem to be outdated and not working anymore, so this package would not meet our quality standards right now. After someone fixes this, feel free to submit a PR!
