### ISSUE TITLE
Add fogleman/primitive

### ISSUE THREAD

**Issue by wI2L** [avelino/awesome-go#2201]
**Description**: Reproducing images with geometric primitives. 
**Link**: https://github.com/fogleman/primitive
**Category**: Images

**Comment by avelino** [comment]
Send PR @wl2L

**Comment by ceriath** [comment]
@wI2L Please fix https://goreportcard.com/report/github.com/fogleman/primitive#golint and add tests, then feel free to submit a PR :)
