### ISSUE TITLE
Add agones to the list

### ISSUE THREAD

**Issue by shersh** [avelino/awesome-go#2240]
Agones is a library for hosting, running and scaling dedicated game servers on Kubernetes
https://github.com/GoogleCloudPlatform/agones

**Comment by ceriath** [comment]
Please submit a PR!

**Comment by ceriath** [comment]
From README: ``This software is currently alpha, and subject to change. Not to be used in production systems.``

Therefore it should not (yet) be on this list. @shersh  Please submit as a PR after it's in a stable state!
