### ISSUE TITLE
How to get the slack invitation link?

### ISSUE THREAD

**Issue by Triple-Z** [avelino/awesome-go#2344]
I have clicked the "join us on slack" badge but it directed me into the slack page which required to sign in the `gophers` slack workspace. How can I get the `gophers` slack workspace invitation link?

**Comment by justinclift** [comment]
This should work:

&nbsp; &nbsp; https://invite.slack.golangbridge.org

:smile:

**Comment by Triple-Z** [comment]
Thx, it does work! On 2019-02-08 21:25 , Justin Clift Wrote: This should work: https://invite.slack.golangbridge.org 😄 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by justinclift** [comment]
@avelino @Triple-Z This can probably be closed now. :smile:
