### ISSUE TITLE
remove go-type-assertion-benchmark

### ISSUE THREAD

**Issue by xuanjiazhen** [avelino/awesome-go#2352]
https://github.com/hgfischer/go-type-assertion-benchmark

This library provides performance benchmarking for two ways to assert. 
But its code is affected by the sprint method, and the result is inaccurate. 
Although the correct code has already been submitted to PR, the author has let it go for a long time.

If you don't see the PR, it is extremely misleading, especially just getting started.

**Comment by ceriath** [comment]
I am closing this issue, if further discussion is required please use the PR #2363
