### ISSUE TITLE
Add toxiproxy - tool for microservice resilience testing

### ISSUE THREAD

**Issue by caalberts** [avelino/awesome-go#2387]
Hi

I’d like to suggest adding toxiproxy https://github.com/Shopify/toxiproxy. I find it great for testing microservice resilience.

I’m happy to open a PR but not too sure which category should this fall into. It’s not exactly in “Testing” as that section applies more to testing go code.

**Comment by cassiobotaro** [comment]
Maybe "Networking" :thinking:

**Comment by caalberts** [comment]
It's already in networking. closing
