### ISSUE TITLE
[QUESTION] Do you accept Go tools implemented in another language ?

### ISSUE THREAD

**Issue by ecstaticcoder** [avelino/awesome-go#2418]
I've released in open source a small Go preprocessor which allows to instantiate generic types and HTML templates.

https://github.com/senselogic/GENERIS

Unfortunately, I've implemented it in D, as this is my favorite language to develop such tools, so would it be completely pointless making a PR to suggest adding it to the Generation and Generics section ?

**Comment by ecstaticcoder** [comment]
So I guess the answer is no... ;)

Anyway, from the go-nuts forum I was already aware that Go developers don't like D at all, as both languages obviously compete against each other in the same development niche, hence my question.

Sorry for bothering you with that pointless proposal :)

Kind regards,

Eric

**Comment by ceriath** [comment]
A pointless proposal is one that you simply close without waiting for a response.

**Comment by ecstaticcoder** [comment]
Indeed ;)

Reopening it...

**Comment by ecstaticcoder** [comment]
Ok obviously you don't have time to answer this simple yes/no question, but I can perfectly understand, as I'm myself maintaining more than a dozend open source tools, and my spare time is thus also very limited.

While obviously this very simple tool is very invaluable to me, as it fixes most design flaws that made Go  incomfortable to use for me, I also know that most Go developers like to use it in a completely idiomatic way (with lots of interface{}, etc), and therefore don't feel any need for generic classes and methods, preprocessor definitions and conditions, HTML templating and Allman style.

And those who do are probably using a mix of existing Go tools (like Genny, etc), which take a much more idiomatic approach to the same problem.

So I'll still make an official PR to your repository when the tool gets 1.0, and then up to you to decide if Generis can be recommended or not to the Go community, as it's implemented in another language.

Kind regards,

Eric
