### ISSUE TITLE
https://awesome-go.com/ shows a Watch Movies website

### ISSUE THREAD

**Issue by complex64** [avelino/awesome-go#2440]
https://awesome-go.com/ shows:

![2019-03-22-224920_1047x598_scrot](https://user-images.githubusercontent.com/63771/54854928-cc032480-4cf4-11e9-8477-5480fdbd71dd.png)

**Comment by kirillDanshin** [comment]
@avelino? O_o

**Comment by avelino** [comment]
sorry

**Comment by complex64** [comment]
No worries, thanks for the fix @avelino
