### ISSUE TITLE
A brilliant error handling library for golang

### ISSUE THREAD

**Issue by SonicRoshan** [avelino/awesome-go#2529]
I have just created a error handling library for golang. https://github.com/SonicRoshan/go-error-handler. If you can check out this library and add it to awesome go, that would mean a lot to me 😋😋😋😋

**Comment by chenbo29** [comment]
> I have just created a error handling library for golang. https://github.com/SonicRoshan/go-error-handler. If you can check out this library and add it to awesome go, that would mean a lot to me 😋😋😋😋

you should need pull request

**Comment by ceriath** [comment]
Please open a pull request!
