### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by hhrutter** [avelino/awesome-go#2542]
https://awesome-go.com/

<img width="489" alt="Screenshot 2019-05-28 at 11 49 56" src="https://user-images.githubusercontent.com/11322155/58468916-c2f06280-813e-11e9-84fe-52bfe7370e52.png">

**Comment by cassiobotaro** [comment]
@avelino can you take  a look?

**Comment by hhrutter** [comment]
aleady up again!
