### ISSUE TITLE
Replace shellwords with go-shellwords

### ISSUE THREAD

**Issue by sergey-shambir** [avelino/awesome-go#2634]
This awesome list suggests [Wing924/shellwords](https://github.com/Wing924/shellwords) which has 1 release (last commit in Oct, 2017), 7 stars and is derived work based on go-shellwords.
Meanwhile [mattn/go-shellwords](https://github.com/mattn/go-shellwords) has 6 releases (last release in Feb, 2019) and 250 stars.

So I suggest to replace shellwords with go-shellwords.

**Comment by ceriath** [comment]
Please submit a PR
