### ISSUE TITLE
periodic review of the projects contained in the list

### ISSUE THREAD

**Issue by avelino** [avelino/awesome-go#2649]
Some reasons we have to do always review:
- Project no longer exists
- Discontinued design
- Design lowered quality
- Any kind of problem

We need to write a software to assist us in this review, if a project comes out of the predefined default open an issue automatically on GitHub, we can not duplicate the issue (happening this would be unsustainable)

**Comment by ceriath** [comment]
I like the idea and agree that this is necessary. However, as of right now, we definitely lack the manpower to do so.
