### ISSUE TITLE
No packages for ftp/sftp.

### ISSUE THREAD

**Issue by shurcooL** [avelino/awesome-go#266]
FTP and SFTP are well defined and widespread standards, yet this list does not contain any Go packages.

Here's a good package for SFTP that I'm aware of:

http://godoc.org/github.com/pkg/sftp

**Comment by mholt** [comment]
Ah cool! I forgot about FTP. Maybe it's best suited for the Networking category...

**Comment by DAddYE** [comment]
For `ftp` I suggest this: https://github.com/jlaffaye/ftp

**Comment by ktsimpso** [comment]
For an ftp `server` https://github.com/koofr/graval Seems to be the most active one I've found.

**Comment by mholt** [comment]
@DAddYE and @ktsimpso and @shurcooL - feel free to add them to the list; Networking would be a fine category for them IMO.

**Comment by shurcooL** [comment]
Is this done?

**Comment by shurcooL** [comment]
I don't think it was done. I'll do it now.
