### ISSUE TITLE
Improve time and star information

### ISSUE THREAD

**Issue by godcong** [avelino/awesome-go#2709]
`Star` allows users to know that the project is more focused.
`Time` is to mark the deadline of star.

The above is just a personal suggestion

**Comment by yinggaozhen** [comment]
@godcong maybe you can try it~ [awesome-go-cn](https://github.com/yinggaozhen/awesome-go-cn/blob/master/README_EN.md)

**Comment by ceriath** [comment]
Could you elaborate more on what you intend to do, since i do not really understand it.

**Comment by kirillDanshin** [comment]
@godcong please see https://github.com/avelino/awesome-go/issues/1266

**Comment by yinggaozhen** [comment]
@godcong 
Maybe you can try this one [awesome-go-cn_en](https://github.com/yinggaozhen/awesome-go-cn/blob/master/README_EN.md). This is a mirror repository of awesome-go. This document repository has **sorted star**, provides **update times**, **archived**, and so on. In addition, this repo also provides the Chinese version. [awesome-go-cn](https://github.com/yinggaozhen/awesome-go-cn/blob/master/README.md)

**Hope this helps you~ :wink:**

**Comment by kirillDanshin** [comment]
@yinggaozhen actually, we could use the results you generate to finally filter out unmaintained items from the original list.

Although I'm not a fan of judging a library by its star counts, I like that you have icons for archived/unmaintained projects

**Comment by godcong** [comment]
@yinggaozhen tks
This is exactly what I want
