### ISSUE TITLE
404 on v8-go

### ISSUE THREAD

**Issue by cryptix** [avelino/awesome-go#275]
Hi,

sadly the `v8-go - V8 JavaScript engine bindings for Go` repository was somehow removed. [mhrdev/v8.go](https://github.com/mhrdev/v8.go) looks like a fork of it (has commits by @idada from oct 2014) but without a copy of the original repo I can't tell where they diverged.

I'm not sure how to proceed on something like this, just a FYI.

**Comment by idada** [comment]
Hi @cryptix.

So sorry. The project is dead. I found 1:1 wrap the V8 engine API is not a good way. If a Go project need V8 engine, the developer can make a wrapper by C++ and provide CGO friendly API to Go. And the GC will more control able.

Thanks.

**Comment by mholt** [comment]
Thanks for letting us know! We like the keep the list clean and current.
