### ISSUE TITLE
A golang tool to list all the files in a website

### ISSUE THREAD

**Issue by deepnum** [avelino/awesome-go#2813]
is there any?

**Comment by deepnum** [comment]
I will pass a url like example.com and it will list all the file available on this domain

**Comment by panjf2000** [comment]
@deepnum 
I believe that you can get what you want by searching on README of awesome-go with your keywords directly instead of opening an issue for it.

So I'm closing this issue, but you are welcome to open another issue if you have new questions.

**Comment by deepnum** [comment]
Reopen this , because the readme doesn't contain any tool to do this
