### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by antimatter96** [avelino/awesome-go#2883]
Website : https://awesome-go.com/

<img width="1440" alt="Screenshot 2019-12-31 at 14 10 08" src="https://user-images.githubusercontent.com/12068176/71615423-4a231e80-2bd7-11ea-9c25-c3547f15a797.png">

First noticed : 8:49 am UTC

**Comment by antimatter96** [comment]
Relates to #2542

**Comment by antimatter96** [comment]
Site is up at https://5e0b00a48f8744c631006a3d--awesome-go.netlify.com/

https://master--awesome-go.netlify.com/ also gives 404

**Comment by panjf2000** [comment]
Maybe we should try to reach @avelino for help.

**Comment by antimatter96** [comment]
@panjf2000 I have no idea how to reach him

**Comment by antimatter96** [comment]
Can anyone from @netlify help @biilmann

**Comment by ceriath** [comment]
it seems to be up right now, so i guess it was a temporary outage
