### ISSUE TITLE
WebAssembly?

### ISSUE THREAD

**Issue by orsinium** [avelino/awesome-go#2933]
There are few links in the official dos:
https://github.com/golang/go/wiki/WebAssembly#interacting-with-the-dom

I think their number will grow. What do you think about adding a section for wasm and putting all these links for the beginning?

**Comment by panjf2000** [comment]
We will consider adding a new category when there are at least three items underneath it.

**Comment by orsinium** [comment]
Great! I will do. The page above has a list of projects in the category but most of them are dead. I've found only a few useful and alive. However, I think, it will be much better soon since go+wasm combo is really promising.
