### ISSUE TITLE
repo.go is missing

### ISSUE THREAD

**Issue by x0rzkov** [avelino/awesome-go#2944]
Hi,

Hope you are all well !

The file repo.go is missing, can you add it please ?

Thanks in advance.

Cheers,
X

**Comment by panjf2000** [comment]
Sorry, I don't quite get it. What's the repo.go file?

**Comment by lucmichalski** [comment]
the repo.go file for generating the markdown

**Comment by lucmichalski** [comment]
https://github.com/avelino/awesome-go/blob/master/Dockerfile#L8

**Comment by panjf2000** [comment]
I see, but it must be gone for a while, have no idea who remove it, I will try to figure it out.

**Comment by lucmichalski** [comment]
thanks

**Comment by orsinium** [comment]
It was @avelino a year ago :)
https://github.com/avelino/awesome-go/commit/ee533006dac8d5782b09989c0038dbabb615c475
If I understand correctly, the motivation is that we don't need it anymore since netlify does the magic.
