### ISSUE TITLE
LiteIDE

### ISSUE THREAD

**Issue by skarllot** [avelino/awesome-go#298]
The best IDE that I used so far.
https://github.com/visualfc/liteide

**Comment by mholt** [comment]
Interesting that it's written in C++ - technically we don't have a spot for software that's not written in Go, but maybe we could make an exception because it appears to be a Go-specific IDE. Submit a PR and put it under Other Software. What do you think @shurcooL ?

**Comment by shurcooL** [comment]
It's a well known Go IDE, I agree it should be added.

**Comment by thoroc** [comment]
+1

**Comment by avelino** [comment]
+1

**Comment by mholt** [comment]
@skarllot Submit a PR and make it so!
