### ISSUE TITLE
Should gorilla/sessions be added?

### ISSUE THREAD

**Issue by monfresh** [avelino/awesome-go#2997]
Hello. I am new to Go (coming from Ruby), and I've been looking for session management and authentication tools similar to what's built into Rails or Devise. I found a bunch of different tools, and one that seems very popular is [gorilla/sessions](https://github.com/gorilla/sessions), which is not listed here. Is there a reason why it's not listed? If not, I'd be happy to open a new PR.

**Comment by panjf2000** [comment]
A PR is always welcome and any repo can be added into the awesome-go list as long as it meets our standards.
