### ISSUE TITLE
goemon - Go Extensible Monitoring

### ISSUE THREAD

**Issue by thoroc** [avelino/awesome-go#301]
[goemon] (https://github.com/mattn/goemon)

Has anyone used this? I just found this lib and I'd like some comment from anyone who might have used it. Seems pretty new. It is from the same author as [gom] (https://github.com/mattn/gom).

**Comment by mholt** [comment]
Is this a lib you want to add to the list or are you just asking about it? To add it, submit a PR. To ask about it, you might have better luck on the go-nuts mailing list, #golang on Twitter, or on the Gopher Slack.

**Comment by thoroc** [comment]
It was just a question. I'll go ask on the mailing list. Thanks. And sorry for the bother.

**Comment by mholt** [comment]
No problem. I just felt bad cause I didn't know the answer and I'm not sure if any of the other collaborators do. Good luck!
