### ISSUE TITLE
[REQUEST] Add `appy` web framework

### ISSUE THREAD

**Issue by cayter** [avelino/awesome-go#3021]
Hi @avelino,

I have just recently finished the initial version of my web framework that is built on top of a few giants listed on `awesome-go`. I hope that doesn't violate any rules that forbids my repository from being listed on `awesome-go`. Thanks!

Repository: https://github.com/appist/appy
Documentation: https://appist.gitbook.io/appy/ (still updating, should be done in the next 2 weeks)

**Comment by panjf2000** [comment]
Please open a PR if you want your repo to be added into the awesome-go list, this is an example: #2968

**Comment by cayter** [comment]
Got it, thanks!
