### ISSUE TITLE
Change name for the package geo_pattern

### ISSUE THREAD

**Issue by pravj** [avelino/awesome-go#305]
Hi folks,

Although the package is already there in the list in [images](https://github.com/avelino/awesome-go#images) section.
But today I made some changes to the project that also involves renaming it to *geoPattern*. Actually I was trying my best to follow the new golang blog, [Package Names](http://blog.golang.org/package-names)

GitHub usually redirects renamed projects very well but I just felt like asking to you all.

So, is this fine to change name for it or not?

**Comment by mholt** [comment]
Yep! Thank you. Just keep it alphabetized and that'll be good! (Feel free to submit a PR)

**Comment by shurcooL** [comment]
I think it's absolutely fine to rename your package.

> Actually I was trying my best to follow the new golang blog, [Package Names](http://blog.golang.org/package-names)

That page says the following:

> The style of names typical of another language might not be idiomatic in a Go program. Here are two examples of names that might be good style in other languages but do not fit well in Go:
> 
> - `computeServiceClient`
> - `priority_queue`

I just want to point out, your new name seems to be equally discouraged in that section like the old. Is that intentional?

**Comment by pravj** [comment]
Ohh my god.

This will obviously indicate that I was not functioning properly when I violated the rule, I wanted to follow.
Probably those `golint` errors, asking me to name underscored variables to CamelCase, made me do the same with package name.

Sorry, my fault. Feeling apologetic.

But a lesson learned.
> I should have shown it to someone before really moving ahead with that desicion.

Thanks @shurcooL, for pointing this out.

So now, can somebody please suggest me, what to name it?
Is `geopattern` fine? It doesn't feel good as a single word though.

**Comment by shurcooL** [comment]
I think `geopattern` is fine. I am not a huge fan of it, but that's the recommended style.

**Comment by pravj** [comment]
Yeah! I'm also not a fan of this convention.
But I renamed it to `geopattern` as you suggested, seems like it was the only option.

All this, resulted in a nice version message though. :smile: 
> [v1.4.1 - The Namesake](https://github.com/pravj/geopattern/releases/tag/v1.4.1)

Made a pull request #306 for it.

Thanks for the help everyone.
