### ISSUE TITLE
Fix #files anchor that conflict with a GitHub

### ISSUE THREAD

**Issue by VadimMalykhin** [avelino/awesome-go#3096]
Anchor ``#files`` has conflict with a GitHub element ``<h2 id="files"  class="sr-only">Files</h2>`` that already in use above repository files listing so we're cannot go to the ``#files`` section using link in the contents.

Rename the ``#files`` anchor name to something else like this ``#Files`` (uppercase the first letter) or ``#files-anchor`` or ``#_files`` etc...

**Comment by ceriath** [comment]
Thanks for reporting! I fixed the issue by 4d97316
