### ISSUE TITLE
lunixbochs/struc is missing

### ISSUE THREAD

**Issue by andig** [avelino/awesome-go#3103]
While not full-featured and with rough edges it provides easy-to-using replacement for pythons pack/unpack. Like binpacker but with better interface. See https://github.com/lunixbochs/struc

**Comment by panjf2000** [comment]
Please open a PR for it. Here is the example: #3056

**Comment by andig** [comment]
Depending on repo owner to enable codecov. Not likely to happen...

**Comment by panjf2000** [comment]
Any tool that provides code coverage service is ok, it doesn't have to be codecov, like https://gocover.io/github.com/lunixbochs/struc, it shows that `struc` has 91% which is good enough for PR.

However there are two code issues in `struc` [golint](https://goreportcard.com/report/github.com/lunixbochs/struc#golint) and [go_vet](https://goreportcard.com/report/github.com/lunixbochs/struc#go_vet) need to be resolved. Do you mind opening a PR to fix those code issues for `struc` or an issue to ask the author to fix those issues?

**Comment by andig** [comment]
Waiting for authors feedback. If ther‘s interest I‘m gonna help out as I‘m using struc myself.
