### ISSUE TITLE
https://awesome-go.com/ says page not found.

### ISSUE THREAD

**Issue by thearyanahmed** [avelino/awesome-go#3122]
![image](https://user-images.githubusercontent.com/20617352/84462413-d2cade00-ac90-11ea-9eac-693d9a1d9cc9.png)

Will the domain be deprecated?

**Comment by panjf2000** [comment]
Last time I checked, https://awesome-go.com/ is available, maybe it's some kind of episodic problem, @avelino could check out the reason if you got some time, thanks~
