### ISSUE TITLE
Add last-commit "badges" to all github repos

### ISSUE THREAD

**Issue by avelino** [avelino/awesome-go#3163]
reference thread: https://github.com/avelino/awesome-go/pull/3154#issuecomment-653872980

**Comment by maguro** [comment]
This is a pretty cool idea.  

The first thing I do when I come here is to open a bunch of tabs, one for each project, to see various metrics.  I think it would be useful to have a set of badges per project so I could see at a glance the lay of the land and drill down to the projects that I'm most interested in.

**Comment by Bahry67** [comment]
Ok
