### ISSUE TITLE
q: how can this repo needs an employ to maintain?

### ISSUE THREAD

**Issue by qlcom** [avelino/awesome-go#3172]
what is happening. I can't understand.

**Comment by qlcom** [comment]
@avelino ?

**Comment by avelino** [comment]
sorry for the delay in answering

Thinking about improving the web project I'm talking to some possible sponsors to withstand the project, and we can finance the contribution of the maintainers, all gains and expenses will be open so everyone can see and understand where every penny goes.

- Improved web version (awesome-go.com), delivering a friendly rendering to Google (SEO) and users locate (filter) the libraries;
- Software to help with automatic revision (as much as possible): many PR stay open for days without attention because we don't have dedicated people in awesome-go (and financially compensated)
- ...

@qlcom do you intend to contribute? We are always open to new contributors.

**Comment by qlcom** [comment]
@avelino no, i am not interested in contributing to this repo. This repo looks very bad. I think i should start one myself. And you don't need money to maintain such a list.

**Comment by avelino** [comment]
I'm sorry, I'm trying to do my best

Do fork, so you don't need to start from scratch the work you can follow from the point you don't agree, the license we use is 100% permissive.

**Comment by phanirithvij** [comment]
Time is money

**Comment by avelino** [comment]
> Time is money, stupid ghosts

@phanirithvij We need help (people) to help maintainers the project, your comment is because you have an interest in helping?

**Comment by phanirithvij** [comment]
@avelino Yes, I'd definitely like to help. Did some investigation at #3404, #3399, #3390, #3341 but I'm not sure how to deal with some of those repos.

**Comment by gabor-boros** [comment]
@avelino do you still need help here?

**Comment by avelino** [comment]
> @avelino do you still need help here?

@gabor-boros all help with awesome-go is very welcome

This was created when the maintainers and I didn't have that much time to look at awesome-go.
Today we have better defined processes for adding new packages, as well as removing outdated packages

[read more here](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md)

how would you like to contribute to awesome-go? by being a proofreader?

If yes, after reading our contribution guide you can start reviewing contributions (pr) using github's own PR reviewer tool

![Screen Shot 2022-03-19 at 18 32 44](https://user-images.githubusercontent.com/31996/159139109-302d9bcc-13f1-4ccc-acb6-daa680f51537.png)

you still won't be allowed to put labels, but that we current maintainers do, the most important thing is you report what the package needs to improve to be accepted in awesome-go - everything is described in the contribution guide

**Comment by gabor-boros** [comment]
FTR: as I understand correctly, maintainers have time nowadays. In this case, feel free to ping me if that changes 😇

**Comment by avelino** [comment]
@gabor-boros You are welcome to contribute, you can help us by reviewing the open contributions, you don't need to be a maintainer to review

**Comment by shrn01** [comment]
I would like to help too. As you said, I can review PRs when I have the time. Love what you are doing here

**Comment by avelino** [comment]
**awesome-go** is open for everyone to contribute, no permission needed, just go to PR and code review on [github (using their code review system)](https://github.com/features/code-review).

Over time you gain level of acceptance PR for branch main

> you are very welcome 💟

**Comment by Sonavan285** [comment]
Sonavan Enterprises Globally Enterprises The World Like Heaven On Earth

**Comment by Sonavan285** [comment]
> @avelino no, i am not interested in contributing to this repo. This repo looks very bad. I think i should start one myself. And you don't need money to maintain such a list.

Come on Let's Do it
