### ISSUE TITLE
Color Libraries

### ISSUE THREAD

**Issue by mazznoer** [avelino/awesome-go#3181]
https://github.com/lucasb-eyer/go-colorful
Color processing library. It can convert color from one space to another, mixing / blending colors, calculate color distance.

https://github.com/mazznoer/colorgrad
Create color scale / color gradient for charts, maps, or creative coding.

**Comment by avelino** [comment]
@mazznoer you can propose the inclusion of these libraries by opening pull request, I recommend reading https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md
