### ISSUE TITLE
Investigate if the package (repository) has not had a commit in over a year

### ISSUE THREAD

**Issue by avelino** [avelino/awesome-go#3211]
Software to help us identify these projects and open an issue automatically to understand the time of the project, if the issue is not answered in X time with positive comment could be removed.

ref: https://github.com/avelino/awesome-go/issues/1446#issuecomment-671497563

**Comment by mrKappen** [comment]
@avelino I added a check for code 302 and 301 as well. The only issue I am still facing is handling hosts other than github

**Comment by mrKappen** [comment]
It might also be a good idea to add a light database that keeps track of flagged issues and does not flag the same issue again for atleast a year. What do you think?

**Comment by avelino** [comment]
> It might also be a good idea to add a light database that keeps track of flagged issues and does not flag the same issue again for atleast a year. What do you think?

at this first moment (version 0.1) I don't see the need, let's feel how the software (script) comes out running on github actions, from there we evolve it to a service containing database

you implement the action for github action?

**Comment by IdiotimaiI** [comment]
Everything sounds confusing.
