### ISSUE TITLE
Fix issues with workflow testing 

### ISSUE THREAD

**Issue by mrKappen** [avelino/awesome-go#3271]
Workflow seems to have had some build issues. I modified the github action. the pr is #3270

**Comment by mrKappen** [comment]
hey @avelino. I noticed that the new workflow seems to have failed to run. I have added some modifications to the workflow that should address the issue.

**Comment by avelino** [comment]
It's not working yet, can you review it?
https://github.com/avelino/awesome-go/runs/1204117398?check_suite_focus=true

**Comment by mrKappen** [comment]
Hey @avelino . Sure thing. I modified the workflow file which should fix the issue. It is scheduled to run every week, so it should run again soon

**Comment by mrKappen** [comment]
Hey @avelino. The test_stale_repositories workflow requires an oauth token in order to be able create an issue. To set this up you need to do the following things:
1. create a personal access token (https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token)
2. add a secret to the avelino/awesome-go repository with the name OAUTH_TOKEN and the value equal to the token that you made

**Comment by avelino** [comment]
> 1. create a personal access token (https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token)
> 2. add a secret to the avelino/awesome-go repository with the name OAUTH_TOKEN and the value equal to the token that you made

done

**Comment by avelino** [comment]
manual run: https://github.com/avelino/awesome-go/runs/1239337829?check_suite_focus=true
issue auto created: https://github.com/avelino/awesome-go/issues/3295
