### ISSUE TITLE
Review all lib hosting in Google Code

### ISSUE THREAD

**Issue by avelino** [avelino/awesome-go#328]
Locate the repository within the github (or another hosting) to change the link

**Comment by mholt** [comment]
Good call. This might take a little time.

**Comment by dgryski** [comment]
Note that many of the github repos might not be "official" repos, but just third-party exports.  I'd make it clear we're looking for the repos where the export was done by the original developer or a seriously interested third party.

**Comment by shurcooL** [comment]
One such example would be #325.

The original repo, https://code.google.com/p/plotinum/, had the following notice at the top:

> ## Plotinum has moved
>
> See http://github.com/gonum/plot instead.

**Comment by dukex** [comment]
The Libraries or Links on google, I found some links to github

- [ ] https://code.google.com/p/portaudio-go/
- [ ] https://code.google.com/p/mlgo/
- [ ] https://code.google.com/p/probab/
- [ ] https://code.google.com/p/go-eco/
- [ ] https://code.google.com/p/gopacket/ -> https://github.com/google/gopacket
- [ ] https://code.google.com/p/go-fn/
- [ ] https://code.google.com/p/go-gt/
- [ ] https://code.google.com/p/gocomplex/
- [ ] https://code.google.com/p/gostat/
- [ ] https://code.google.com/p/mudlark-go-pkgs/
- [ ] https://code.google.com/p/gomock/
- [ ] https://code.google.com/p/gographviz/ -> https://github.com/awalterschulze/gographviz
- [ ] http://godoc.org/code.google.com/p/rspace.cmd/doc -> http://godoc.org/robpike.io/cmd/doc
- [ ] http://godoc.org/code.google.com/p/go.tools/cmd/goimports -> http://godoc.org/golang.org/x/tools/cmd/goimports
- [ ] https://code.google.com/p/gocc/

**Comment by matrixik** [comment]
Not perfect, but all google code links removed. Some by original authors, some by others that fixed import links and added some more commits.

**Comment by avelino** [comment]
good work :D
