### ISSUE TITLE
Changelog of a sort - to follow easily what was added and when

### ISSUE THREAD

**Issue by uded** [avelino/awesome-go#3308]
Currently I am an observer on Github, but this is a very inconvenient way to follow what is new on this awesome list. It would be great if there could be a changelog with dates or some other form available to see newly added libraries, projects, etc. 

Maybe using semantic commits for that? Then the changelog can be actually easily generated...

**Comment by avelino** [comment]
I agree that this feature would be great, but we need to think about how to generate this changelog automatically.

It can be done by looking at the commit history and taking the diff to know what was changed, since this software is done, we can configure a cronjob (via GitHub action) to run once a week and generate a new structured markdown file and generate an html page for the site.

What do you think about this architecture above, makes sense? @uded could you contribute with this implementation?

Here's an example and job implementation that we run weekly, write by @mrKappen: 
- https://github.com/avelino/awesome-go/issues/3211
- source: https://github.com/avelino/awesome-go/blob/master/test_stale_repositories.go
- job: https://github.com/avelino/awesome-go/blob/master/.github/workflows/run-check.yaml

**Comment by uded** [comment]
It's doable as long as there is a format of the commit message which we can follow. Hence my suggestion would be to use something like semantic commits, which can structurize the message. I.e.:

```
added(databases): https://github.com/project/path
deleted(network): https://github.com/project/path
```

I am open for suggestions here on what would be the best format, but if we can enforce that the rest is easy to do...

**Comment by avelino** [comment]
ensure standard in commit would say it is impossible, many people do not follow the pull request template, I do not believe they will follow pattern to commit

we need to create an "intelligence" that identifies this in the received patch (git commit), example:
https://github.com/avelino/awesome-go/commit/d021e7af7d03718da37d53a54eabc95919d827cf?branch=d021e7af7d03718da37d53a54eabc95919d827cf&diff=unified#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by mrKappen** [comment]
you could perhaps use the heading to determine which category the added item would fit in and use that to create the changelog. That way you wouldn't have to rely on users following a particular format. This would also be backwards compatible and you could create the change log from the very beginning of this repo. Granted, this isn't a perfect solution, but it might be a decent enough way forward

**Comment by uded** [comment]
@avelino I think we can enforce some standards - using hooks. Sorry, if you want a standardization then just follow it or go away, simple as that. So instead of trying to work around people who do not care, maybe we shouldn't care instead. Simple as it is to implement a mechanism to create a changelog with a proper commit message, trying to figure out how to go around a problem of freely formatted messages will always create issues down the road...

Also, I would think that creating a history changelog makes no sense right now. Just cut a fine line and say from now we gonna make it. Otherwise, the effort required to figure out how to make a changelog for all past commits is a high effort task. And, IMHO, time wasted. Since it was not there before just accept it. It is what it is...

**Comment by uded** [comment]
After some investigations what I can see is a couple of options.

1. Conventional (well, sort of) commits + custom scripts
This is a rather simple solution in which AwesomeGo will have that enforce a format of each commit message to follow strict rules. We can use one of the GithubApps for that, as listed above. The format that I would be suggesting was also mentioned above: `[added|removed]({{category}}): {{name of the library}} - {{description}}`. Theoretically, this will allow us to create a nice, category based changelog updated on every commit. 
2. Somewhat conventional commit with GithubApps
Since we really do not need much my suggestion would be to minimize the effort, scripting (which sooner or later will break or will require adjusting), etc. we can use two Github apps - one to enforce the format of the PR message according to our rules (most of the above will do), and [the second one to create changelogs automatically](https://docs.changelogg.io/features#create-public-links-for-changelog-which-can-be-shared-with-everyone-keep-your-users-in-the-loop-with-the-teams-awesome-progress). Using this combo we minimize any impact on the repository, current workflow, etc.
3. Custom scripting
This is tricky. We can use some scripts to parse each commit content of the README.MD file and create a changelog. It will work but will require a substantial amount of effort to make it right. Theoretically, we have everything there, but it's not given and not ready to be used by any of the external tools known to me.

**Comment by uded** [comment]
BTW, is there a way to vote here? Would be nice :-)
