### ISSUE TITLE
test stale repositories workflow re-flags repositories once the issue that flagged them has been closed 

### ISSUE THREAD

**Issue by mrKappen** [avelino/awesome-go#3339]
The workflow checks if a repository has already been flagged by parsing through existing, open issues with the expected title format and sees if they have already been mentioned. This breaks once the issue is closed.

**Comment by avelino** [comment]
@mrKappen Do you have any proposals to correct this problem?

**Comment by mrKappen** [comment]
Hey @avelino, I was thinking of implementing some kind of database to remember handled issues. 

Here is a potential project that might be useful: https://github.com/mapbox/hubdb

Since our database would be really simple, we could opt to just have github repo and use issues as a way to remember things. What do you think?

**Comment by avelino** [comment]
Yes, we can use it, can you structure the project?
