### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [avelino/awesome-go#335]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by avelino** [comment]
You're not the first to make this proposal, follows the history of another conversation, my thinking hasn't changed
https://github.com/avelino/awesome-go/issues/112

**Comment by jeffreyjackson** [comment]
So you wouldn't be opposed to it if we had others come on board right?  we would still want you as an admin going forward of course.

**Comment by avelino** [comment]
If other "awesome-*" (python, ruby and others) migrate I take awesome-go!
But I don't see a whole lot of sense to centralize it. As you saw in issue #112, the @ionutvmi gave up.

**Comment by avelino** [comment]
The awesome[1] does exactly what you're proposing.

In my view, to centralize in a quality organization list (go, python, and others) will fall, people who don't use technology X will accept the PR without knowing.

[1] https://github.com/sindresorhus/awesome

**Comment by avelino** [comment]
sample: https://github.com/razum2um/awesome-clojure/issues/26

**Comment by dukex** [comment]
I think the https://github.com/sindresorhus/awesome ideia is better than a big central organization

**Comment by jeffreyjackson** [comment]
@dukex the issue is that 1 person is responsible for all of the PRs.  If it were an org we could implement a self sustaining process.  Look at some of the more popular repos on github.  They succeed through sustainability, and thats easier with an org.

**Comment by avelino** [comment]
@jeffreyjackson In awesome-go It's not only me who accepted PR. Gave access for meritocracy, like any open source project.

@shurcooL
@mholt
@dukex
@hoffoo

If you see Help "awesome-go" is fair you (or which wants to person help) get access!

**Comment by avelino** [comment]
It seems to me that the idea wasn't too far forward, correct me if I'm wrong. I'm closing the issue which you want thing you open again.
