### ISSUE TITLE
Add section for Go Trainers/Companies

### ISSUE THREAD

**Issue by corylanou** [avelino/awesome-go#3386]
What are your thoughts on adding a section for Go Trainers?

Here are a couple I know of to start with, but I suspect it would grow:

## Training Companies offering Go Workshops and Courses

* [353Solutions](https://www.353solutions.com/workshops) - Offers Go Workshops
* [Ardan Labs](https://www.ardanlabs.com/training/) Go Corporate & Individual - Specialized Training Solutions
* [Gopher Guides](https://www.gopherguides.com/) - Go training in person and virtual with topics from beginner to advanced, profiling, web development, advanced testing, and more.

**Comment by phanirithvij** [comment]
+1, Also suggest it under Resources, below websites and move tutorials above websites

```
Resources
    Tutorials
    Websites
    Training
```

**Comment by avelino** [comment]
Having 3 or more items we can create a new category, we talk about it in the [contribution guide](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md).

@corylanou do you send PR with the change (update)?

**Comment by avelino** [comment]
I am closing this issue, want to add a new category, package, site, etc, send pull request

it is important to read the contribution guide before
https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md
