### ISSUE TITLE
Add podcasts section or mention it

### ISSUE THREAD

**Issue by phanirithvij** [avelino/awesome-go#3407]
Golang wiki has it https://github.com/golang/go/wiki/Podcasts

Also Newsletters
https://til.hashrocket.com/go
https://golangweekly.com

**Comment by avelino** [comment]
Sounds like a good topic to me, do you send PR?

**Comment by tarunj096** [comment]
I don't find podcasts section, Is it yet to be added ? 
Should I send a PR?

**Comment by avelino** [comment]
I am closing this issue, want to add a new category, package, site, etc, send pull request

it is important to read the contribution guide before
https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md
