### ISSUE TITLE
Why are some PR's ignored?

### ISSUE THREAD

**Issue by norwack** [avelino/awesome-go#342]
It seems to be pretty common that ALOT of PR's are ignored, whys that?

**Comment by mholt** [comment]
A lot of PRs come in and the only way we know about them is from our news feed. (Maybe other collaborators get emails for Watched repos, but I don't.) Although each changed line only takes a few minutes to look over, that context switch can be inconvenient if we're in the middle of something else. Consequently, some make it through sooner and others don't. Sorry about that.

A couple weeks ago I spent about a half hour closing out nearly all the issues and PRs in one fell swoop. I'll try to spend a few extra minutes tomorrow to look over each submission that's pending, including yours, and get them all closed up. (But a couple of current PRs have merge conflicts or other edits that need to be made first.)

**Comment by avelino** [comment]
We need more people to collaborate, if wanted welcome, I add you.

**Comment by shurcooL** [comment]
Another minor point, having to verify that the added/changed/moved entries are in alphabetical order is discouraging. That's something computers are better at than humans (at least me).

**Comment by garymoon** [comment]
(Long-time lurker, first-time poster, hi all!)
I had that thought while reading the comments here also, but couldn't think of how we'd make that happen at the time. Any ideas @shurcooL?

**Comment by mholt** [comment]
I know you didn't ask me but I might as well post the obvious idea: write a script that could be stored in a public Gist which we can run to check alphabetical order.

It could be Javascript which can just be pasted into the dev console when viewing README.md... maybe?

**Comment by dgryski** [comment]
@mholt Travis script is the best idea since it will report failures on the pull request itself.

**Comment by shurcooL** [comment]
It is possible to write a Travis script that runs a Go program that parses `README.md` using `blackfriday`, and for all unordered lists of links it finds, verify they are in sorted order.

A better idea IMO, instead of having something that _verifies_ whether it's in sorted order or not, is something that _makes_ it sorted. So humans can focus on just adding/removing things from sections without caring about sorting order, and some automated process would sort everything.

I'm less sure how to make the latter possible.

**Comment by garymoon** [comment]
My thought was that it wouldn't be at all worth the time and effort to run a script on the file - the brain isn't quite that bad at the task. I was thinking more about how can we ensure at display time that everything is alphabetized. Still not possible I guess.
