### ISSUE TITLE
Suggestion: Awesome io/fs

### ISSUE THREAD

**Issue by tooolbox** [avelino/awesome-go#3437]
With [`io/fs`](https://tip.golang.org/pkg/io/fs/) on the horizon, there are compatible packages starting to pop up, such as [memfs](https://github.com/psanford/memfs), [hashfs](https://github.com/benbjohnson/hashfs), and [gistfs](https://github.com/jhchabran/gistfs).  These may or may not be entirely serious and certainly are not mature given the package they depend on is not yet released, but I thought it might be helpful to the community to have a list of `io/fs`-compatible packages.  This could be either its own listing, or perhaps within the `File Handling` section with little `io/fs` badges next to the compatible ones.

This is just a suggestion.  Thanks for keeping this list together, and Happy New Year!

**Comment by johejo** [comment]
There is an official in-memory implementation.
https://github.com/golang/go/blob/master/src/testing/fstest/mapfs.go

And I created [ghfs](https://github.com/johejo/ghfs).

**Comment by avelino** [comment]
> perhaps within the File Handling section with little io/fs
@tooolbox sounds like a great idea, can you contribute with this update?

is compatible with our [contribution guide](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines)
> At least 3 items are needed to create a new category;

**Comment by avelino** [comment]
Closing the issue for lack of interaction
