### ISSUE TITLE
Dependency Injection: Google Wire

### ISSUE THREAD

**Issue by alexeymaximov** [avelino/awesome-go#3473]
There are [Fs02/wire](https://github.com/Fs02/wire) in the [Dependency Injection](https://github.com/avelino/awesome-go#dependency-injection) section.

Is it might make sense to add the fairly popular [Google Wire](https://github.com/google/wire) project too? ([blog.golang.org/wire](https://blog.golang.org/wire))

**Comment by avelino** [comment]
If the project fits into a category and passes the minimum quality requirement requested by the awesome-go list, yes. I [recommend reading](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md)

Do you send PR by adding the project?

**Comment by avelino** [comment]
I am closing this issue, want to add a new category or package send pull request

it is important to read the contribution guide before
https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md
