### ISSUE TITLE
Two Recommendations.

### ISSUE THREAD

**Issue by 33nano** [avelino/awesome-go#3481]
[Go-IPFS](https://github.com/ipfs/go-ipfs) and [what-anime-cli](https://github.com/irevenko/what-anime-cli)

**Comment by avelino** [comment]
Awesome-go is a mother's heart, always fits more person (project)

Send PR putting the project on the list, I recommend reading the [contribution guide](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md) and when opening the pr fill out the issue template
