### ISSUE TITLE
Color scale library

### ISSUE THREAD

**Issue by mazznoer** [avelino/awesome-go#3519]
Repo: https://github.com/mazznoer/colorgrad

Does it fit in here?
If it fit, what category should I put it in?

**Comment by avelino** [comment]
Awesome-go is a mother's heart, always fits more person (project)

Send PR putting the project on the list, I recommend reading the [contribution guide](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md) and when opening the pr fill out the issue template
