### ISSUE TITLE
emoji on topicos (titles)

### ISSUE THREAD

**Issue by avelino** [avelino/awesome-go#3550]
This week @github company announced the new way of rendering the **README**, where the menu is generated automatically (table of content), in the shared gif (example repository https://twitter.com/github/status/1376636651963842562) the topics had emoji and in my opinion gives a more friendly look to the project (especially in the menu)

What is your opinion about using emoji.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/31996/112977118-11505d00-912c-11eb-87bd-abe8f93f76df.gif)

**Comment by Joakker** [comment]
Personally I love it. It would make the sections a lot more distinguishable from each other for sure

**Comment by avelino** [comment]
> Personally I love it. It would make the sections a lot more distinguishable from each other for sure

Can you contribute to this update by sending pull request?

**Comment by Joakker** [comment]
Sure

**Comment by avelino** [comment]
I did some tests and putting emoji will not work properly the generation of the html site

I'm closing this issue
