### ISSUE TITLE
Broken link 404 (minor issue)

### ISSUE THREAD

**Issue by manuelbcd** [avelino/awesome-go#3551]
I just discovered by chance that this link is broken

![image](https://user-images.githubusercontent.com/10448961/113114402-978fa080-920b-11eb-9f3c-74f0feb7f496.png)

Link: https://myanimelist.net/modules.php?go=api

Response: 
![image](https://user-images.githubusercontent.com/10448961/113114440-a37b6280-920b-11eb-8599-f82c42004755.png)

I think we need to contact PR owner to have the right URL.

**Comment by avelino** [comment]
version 2 of the API has appeared, here is the documentation https://myanimelist.net/apiconfig/references/api/v2

@manuelbcd do you send PR updates?

**Comment by manuelbcd** [comment]
Sure @avelino , here we go
