### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by MatejMagat305** [avelino/awesome-go#3566]
verry good library: [gioui/gio](https://github.com/gioui/gio) or(same but own site) [gioui.org](https://gioui.org/)

**Comment by avelino** [comment]
you can propose a project addition by sending PR, but I always recommend that the maintainers of the project do this, but why?

We have a contribution guide that asks for a minimum quality for the project to be accepted, see here the contribution guide
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

If you are not sure that the project passes all the points I recommend to open an issue in gioui proposing the maintainers to send the PR in awesome-go

**Comment by avelino** [comment]
I am closing this issue, want to add a new category or bibliote send pull request

it is important to read the contribution guide before
https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md
