### ISSUE TITLE
Question before PR

### ISSUE THREAD

**Issue by gboddin** [avelino/awesome-go#3619]
Hi, I've came across a few applications/libraries lately mostly in the Security/Pentesting category.

I was wondering if it's worth having 2 security category :

- Application security ( renaming the actual security category ? )
- Security automation

A few examples :

https://github.com/projectdiscovery/nuclei
https://github.com/v-byte-cpu/sx
https://github.com/LeakIX/l9explore

**Comment by avelino** [comment]
yes, having 3 or more packages per category is fine 

Can you send this contribution (PR)?

**Comment by gboddin** [comment]
Looking into it, I have to check the coverage for some of those
