### ISSUE TITLE
Generate the site in HTML

### ISSUE THREAD

**Issue by dukex** [avelino/awesome-go#363]
Like the @avelino did mention in https://github.com/avelino/awesome-go/pull/347, now with travis build we can generate a google friendly website

I dont know what is the better approach, I found two posts about
http://awestruct.org/auto-deploy-to-github-pages/
https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db

What do you think @avelino ?

**Comment by avelino** [comment]
+1

**Comment by avelino** [comment]
@kirillDanshin this issue

**Comment by avelino** [comment]
@kirillDanshin evolve this issue?

**Comment by kirillDanshin** [comment]
@avelino yep, I'll done with it soon. I'm working in my private repo.
the new website is based on React.js and will be really awesome :wink:

**Comment by kirillDanshin** [comment]
@avelino check out PM on gitter ASAP please
