### ISSUE TITLE
Suggestion: Add Track Awesome List

### ISSUE THREAD

**Issue by theowenyoung** [avelino/awesome-go#3649]
Hi, @avelino :

I'm Owen, a big fan of awesome-go. After discovering this awesome list, I read all kinds of interesting items in the entire list. After that, I wanted to see what updates were made to this list every once in a while, and had to go through Github's commit history to see what was updated for each commit. To be honest, it was quite a poor reading experience.

So for this need, I created [Track Awesome List](https://www.trackawesomelist.com) in my spare time, and created a profile for awesome-go, https://www.trackawesomelist.com/avelino/awesome-go . With this link, we can read the latest updates of awesome-go by day/week, free, daily updated. I wonder if anyone else has this need to see the latest updates, and if so, whether to add this link somewhere in the readme to tell others they can see the updates via this link?

I also created a badge for awesome-go, which can also be linked to the timeline of awesome-go.

[![Track Awesome List](https://www.trackawesomelist.com/badge.svg)](https://www.trackawesomelist.com/avelino/awesome-go/)

```bash
[![Track Awesome List](https://www.trackawesomelist.com/badge.svg)](https://www.trackawesomelist.com/avelino/awesome-go/)
```

Let me know what you think. I'm happy to receive any feedback or suggestions for improvement. I want this to be as useful as possible.

If you don’t think it’s necessary, that’s okay. I really appreciate you maintaining such an awesome list. I like this list.

**Comment by avelino** [comment]
@theowenyoung what do you think about having a history page on awesome-go.com?

**Comment by theowenyoung** [comment]
Hi, thanks for your reply. 

What do you mean exactly? Add a link on awesome-go.com? or add a page on awesome-go.com?

**Comment by avelino** [comment]
Add a page awesome-go.com/history

Cheers,
Avelino
Schedule a meeting with me, here ( https://meet.avelino.run/avelino )

Apologies for any typos. I’m all thumbs.

**Comment by theowenyoung** [comment]
which way do you prefer to add this page? an embed page? Cause trackawesomelist.com is a static site, and https://www.trackawesomelist.com/avelino/awesome-go/ is checked and built every day. 

I supposed just  placing a link somewhere is simpler.
