### ISSUE TITLE
Recommendation:

### ISSUE THREAD

**Issue by shreyaskapale** [avelino/awesome-go#3658]
Go ping is a ICMP package for Go
Rep URL : https://github.com/go-ping/ping

**Comment by informeai** [comment]
> Go ping is a ICMP package for Go
> Rep URL : https://github.com/go-ping/ping
Hello shreyaskapale. ✋🏼 
You can fork and add your package to the README.
Just check which segment your package is best suited for, and then send a pull request. 👍🏼
