### ISSUE TITLE
Recommendation:

### ISSUE THREAD

**Issue by larryhu** [avelino/awesome-go#3726]
Codis is a proxy based high performance Redis cluster solution written in Go. It is production-ready and widely used at wandoujia.com and many companies. You can see Codis Releases for latest and most stable realeases.

Rep URL :  https://github.com/CodisLabs/codis

**Comment by avelino** [comment]
if you are part of the team that maintains codis, or saw that it meets the minimum requirement to join awesome-go just open a pull request, I will be very pleased to review your contribution

https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md
