### ISSUE TITLE
Higher level separation.

### ISSUE THREAD

**Issue by dmitshur** [avelino/awesome-go#38]
Currently, there are two high level categories:
- Awesome Go
  - Both importable Go libraries, but also DevOps tools, Utilities, etc.
- Resources

I would change that to be three:
- Awesome Go
  - (Only importable Go libraries that people would use in their code)
- Go Tools
  - (Go binaries, plugins for editors, websites like gocover.io, etc., but no importable code)
- Resources

---

Some currently missing _must have_ things:
- Awesome Go
  - API Bindings
    - github.com/google/go-github - GitHub API bindings
  - OpenGL
    - [x] github.com/go-gl/gl - OpenGL bindings
    - [x] github.com/go-gl/glfw3 - glfw3 bindings
    - [x] github.com/errcw/glow - OpenGL bindings (via generation)
    - [x] github.com/go-gl/mathgl - Vectors, Matrices, other math
- Go Tools
  - Development Tools
    - goimports - drop-in replacement for gofmt, updates your Go import lines, adding missing ones and removing unreferenced ones.
    - [doc](http://godoc.org/code.google.com/p/rspace.cmd/doc) - CLI tool by Rob Pike, has a convenient interface, e.g., `doc fmt.Println` to see docs for Println
  - [x] Editor Plugins
    - [x] Sublime Text
      - [x] https://github.com/DisposaBoy/GoSublime - Golang plugin collection for the text editor SublimeText 2 providing code completion, etc.

Thank you!

**Comment by Mandown745** [comment]
Thanks
