### ISSUE TITLE
Changes not appearing on website https://awesome-go.com/

### ISSUE THREAD

**Issue by TheArchDev** [avelino/awesome-go#3815]
I've noticed that some recent changes (eg #3805 #3807 #3808 ) merged a couple of days ago have yet to propagate to the public website hosted at https://awesome-go.com/ . What's the process (manual or automated) for such code changes in the repo appearing on that website too? Maybe the process could be captured in the CONTRIBUTING.md file for contributors to understand?
Thank you!

**Comment by kitarp29** [comment]
@TheArchDev I have some past experience in Web Developement.
I think I can help with this issue.
Please assign it to me.

**Comment by carlmjohnson** [comment]
It looks like this is still a problem. Are the devs aware of this? @avelino?

**Comment by avelino** [comment]
for some reason travisci stopped working, I created an issue to migrate to github actions #3943

**Comment by carlmjohnson** [comment]
Thanks!

**Comment by avelino** [comment]
> Thanks!

@carlmjohnson Thank you for creating the issue notifying of the problem
