### ISSUE TITLE
new website for the repo

### ISSUE THREAD

**Issue by fernandobelotto** [avelino/awesome-go#3993]
Hi guys,

i created a docusaurus website based on the repo to facilitated the usage and i deploy to vercel. I found the repo quite useful and i would like to contribute linking the site in the repo. What you guys think? 

here is the link to checkout [link](https://go-awesome.vercel.app)

**Comment by avelino** [comment]
@fernandobelotto I like the idea of having a new layout (site) for awesome-go, what worries me is how do we keep the site up to date with automation being done in the readme?

Today we have a go code that generates the site based on the readme content

How do you do to automatically convert the awesome-go readme to Docusaurus format? I know it is readme, but there is a structure of its own.

Another point is sub-pages (SEO), read more here #3957

**Comment by fernandobelotto** [comment]
the website at the https://go-awesome.vercel.app/ uses markdown files to generate the content, so we can have a way to make the site point to the original readme and keep aways up to date. To make the side bar struct i indeed break the original readme in other smalls markdown files in but i think we can solved that with a script

**Comment by avelino** [comment]
Let's schedule a call to talk about this project?
https://cal.com/avelino/45min

**Comment by apoorvcodes** [comment]
I'll be interested in site maintenance, cos I have been a long term docasaurus user

**Comment by avelino** [comment]
@fernandobelotto how is the process of split the **README** into several **markdown** files going?
need any help?
