### ISSUE TITLE
can't pkg.go.dev list packages like it's listed in pub.dev (dart)

### ISSUE THREAD

**Issue by zriyansh** [avelino/awesome-go#4007]
pkg.go.dev makes it so hard to discover 3rd party packages, where to find if someone makes a cool Go package? Can we rely solely on awesome-go? These guys are already working hard to make it up to date for us. 

pub.dev allows us to see packages that I can use (not search for the one I need). Here the image. 

<img width="620" alt="Screenshot 2022-01-26 at 00 17 39" src="https://user-images.githubusercontent.com/52788043/151039615-c910574e-a889-4552-9515-ca0ebb00b1e5.png">

Why is Google not listing/categorizing packages? on pkg.go.dev, at least show us which were the most imported one of the week/month/year/all-time. 

I want to include innovative packages that do something useful, but if I do not know they exist or not, how could I possibly even think about using them?

This is Go's package page. 
<img width="644" alt="Screenshot 2022-01-26 at 00 17 30" src="https://user-images.githubusercontent.com/52788043/151039882-be2e0e64-6f25-4be2-98ae-549443da214d.png">

Feel free to close the issue, I raised it just because I couldn't find the answer to this.

**Comment by phanirithvij** [comment]
@zriyansh I suggest you check if an existing issue exists or file a new issue over at https://golang.org/s/pkgsite-feedback (from the README of https://github.com/golang/pkgsite)

Also refer: https://go.dev/blog/pkgsite
