### ISSUE TITLE
tests: the sub items (with 3 hash marks `###`) are staying in the main list

### ISSUE THREAD

**Issue by avelino** [avelino/awesome-go#4026]
not respecting the hierarchy and making it impossible to test the alphabetical order

https://github.com/avelino/awesome-go/blob/5f680d4c62c7275d40191a05c7772f17a0b2a1ae/repo_test.go#L23-L27

**Comment by Kwynto** [comment]
I wanted to solve this problem.
I spent several hours checking this error, but I could not find the described problem.
Alphabetical sorting works fine for me and section heading levels do not affect the test results.
I created a separate branch for myself and tried to change the README.md and section headers in different ways to simulate an error, but I did not find the effect of headers on sorting.
TestAlpha() together with testList() and checkAlphabeticOrder() show an alphabetic order violation only if there is one.

Perhaps this issue needs to be closed?

**Comment by Cori1109** [comment]
Great job!
