### ISSUE TITLE
Test coverage requirement for template / starter repos?

### ISSUE THREAD

**Issue by mikestefanello** [avelino/awesome-go#4036]
I've been wanting to submit my project, [pagoda](https://github.com/mikestefanello/pagoda) to _awesome-go_ but the test coverage requirement is a problem for two reasons. [Pagoda](https://github.com/mikestefanello/pagoda) is a full-featured, rapid, full-stack web development starter kit (built on top of [Echo](https://github.com/labstack/echo) and [Ent](https://github.com/ent/ent)). The problems are that:

1) A very large amount of code is [generated](https://github.com/mikestefanello/pagoda/tree/main/ent) from [Ent](https://github.com/ent/ent), which is an ORM. This generated code does not generate tests so the overall coverage percentage for the project is automatically dropped very low.

2) With this project being a starter kit / base, it includes a lot of code that is purely for example (especially the _routes_) to highlight features, functionality and developer patterns. These don't contain tests because they are expected to be deleted by anyone using this template for an actual project of their own. I may provide some test coverage for the most functional routes at some point.

If you remove these two things, the coverage would be extremely high, but with them, it's somewhere around 25%.

Does that exclude this project from being included or is the test coverage requirement not applicable to projects like this?

**Comment by avelino** [comment]
@mikestefanello we have a category especially for this type of project.

Even though there is an automated check process, it was developed to help awesome-go maintainers, not for inclusion or exclusion of projects (proposed inclusion via pull request).

> I quickly looked at the **pagoda** project and liked the documentation contained in the README, you really took care with the people that are going to use the project layout, 🎉  congratulations on your work.

I would have no problem with pagoda joining awesome-go, but we need to see what other maintainers think.
Open a PR proposing to include pagoda in awesome-go (in the category mentioned above) and link this issue there.

**Comment by mikestefanello** [comment]
Hey @avelino - thanks for the help, great feedback and consideration to have my project included. I opened a PR: https://github.com/avelino/awesome-go/pull/4038
