### ISSUE TITLE
Add gominima in framework section

### ISSUE THREAD

**Issue by apoorvcodes** [avelino/awesome-go#4050]
Hey there fellow gophers, this is maintainer and author of gominima a super fast go web framework with 0 deps and fully compatible with net/http. Here is the repo https://github.com/gominima/minima, also a star would be great help. I wanna add this framework to the framework section.

**Comment by apoorvcodes** [comment]
@avelino So i should hit with a pr?

**Comment by phanirithvij** [comment]
Yes please do, one of the maintainers will review it within a day.

**Comment by avelino** [comment]
@apoorvcodes we are waiting for your contribution via pull request, I will close this issue.
