### ISSUE TITLE
Consider rakyll/go-hardware?

### ISSUE THREAD

**Issue by shurcooL** [avelino/awesome-go#409]
There is a new directory for hardware related libraries, tools, and tutorials for Go.

https://github.com/rakyll/go-hardware

See https://twitter.com/rakyll/status/600007636579266560 for the announcement. /cc @rakyll

Awesome-go list already has a [hardware section](https://github.com/avelino/awesome-go#hardware), but it's pretty brief. It contains two libraries, both of which are already a part of go-hardware list.

Honestly, it seems the easiest and best option would be to simply replace our hardware section with a reference to go-hardware. Go-hardware seems a lot more thorough, complete, and targeting Go hardware side specifically. Thoughts?

**Comment by shurcooL** [comment]
The other options are to simply add a link to go-hardware without removing the current hardware section (which seems not ideal, given the overlap).

Also, perhaps @rakyll would want to instead integrate go-hardware into awesome-go, by expanding the Hardware section, and moving the current entries into here. Only if she actually wants to do that, and you @avelino is willing to give her push rights here, etc.

The last option is to do nothing at all and simply close this issue.

**Comment by dukex** [comment]
To me remove our hardware section and link go-hardware is better.

**Comment by 0xCMP** [comment]
I agree with @dukex. They have a nice set of hardware packages already which they could continue to keep tabs on.

**Comment by shurcooL** [comment]
Ok, I've made #410 that resolves this, please review.
