### ISSUE TITLE
proposal: create an ARCHIVE.MD

### ISSUE THREAD

**Issue by switchupcb** [avelino/awesome-go#4200]
Instead of removing projects, it may be useful to archive them. This can be implemented using a bot that _(on update)_:
1. Parses raw markdown from README.MD: https://github.com/yuin/goldmark
2. Checks library URLs with the Github API for archive status: https://docs.github.com/en/rest/repos/repos#get-a-repository
3. Remove archived libraries from the README _(delete the line from the MD)_.
4. Add the removed library to the ARCHIVE.

Instead of "deleting" the line, simply iterate line by line and include it when necessary.
```go
var ARCHIVE strings.Builder
var README strings.Builder

// content represents the lines or file.
for _, line := range content {
    repo := getRepository(line)

    // add conditions where necessary
    switch {
      case repo.archive:
        ARCHIVE.WriteString(line)
      default:        
        README.WriteString(line)
    } 
}
```

You could also add reasons for archive in that README such as _archived_, _standards_, etc.

**Comment by phanirithvij** [comment]
Just adding to this, the current process is manual.
Usually when a project is archived it's eol (abandoned) and thus in such cases a community/other fork will replace the one in the readme if there is one.
This is the more important part where we need to focus, I believe than to maintain a list of old abandoned projects.
