### ISSUE TITLE
Question: Which category should a web project generator be?

### ISSUE THREAD

**Issue by didip** [avelino/awesome-go#422]
[go-bootstrap](http://go-bootstrap.io/) generates new web project for users, it is not a web framework.

Which category should it fall under?

**Comment by mholt** [comment]
As much as I dislike putting things in Miscellaneous, that does seem to be a good fit. It's a neat, but kind of niche, tool.

**Comment by avelino** [comment]
Miscellaneous or Command line (Your project is a command line that generates a web application structure)
