### ISSUE TITLE
Discussion on removal of Stack up (sup)

### ISSUE THREAD

**Issue by phanirithvij** [avelino/awesome-go#4329]
[Stack Up](https://github.com/pressly/sup) added in https://github.com/avelino/awesome-go/pull/651

Has no tests. Ref:
- https://github.com/avelino/awesome-go/pull/4279#issuecomment-1171437508
- https://github.com/pressly/sup/issues/179

**Comment by Kwynto** [comment]
I really dislike tests, but tests have to be written and quality standards require it.
However, CONTRIBUTING.md prescribes:

> if the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. (Note: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results);

In this case, the code is not testable and possibly non-idempotent.
I think it's inappropriate to apply test coverage rules to such projects.
These projects may very well be on the "awesome-go" list. IMHO
