### ISSUE TITLE
Remove stale action

### ISSUE THREAD

**Issue by ceriath** [avelino/awesome-go#4479]
I think we should remove the stale action. There is no real reason for it to be there, since most PRs are going stale, because none of us Maintainers got to review it in time. I don't think that is how it should work.

IF we want to keep it, we should modify it, so it only marks PRs as stale, that are labeled "pending submitter response".

**Comment by avelino** [comment]
@ceriath thank you for proposing improvement in our workflow
the stale was really getting in the way (and not helping), I removed it
