### ISSUE TITLE
Non-go utilities for go development

### ISSUE THREAD

**Issue by eapache** [avelino/awesome-go#451]
I wrote/maintain Starscope, a project for code search that happens to support Go but is written entirely in Ruby. It's a critical piece of my personal Go development workflow, but since it's not actually written in Go I'm not sure it belongs on this list?

Could you clarify please if utilities that are useful to gophers but are not themselves written in go are eligible to be submitted?

https://github.com/eapache/starscope

**Comment by shurcooL** [comment]
I think it only has to be written in Go if it's a library.

If it's a tool useful for Go development, just make sure it goes somewhere in https://github.com/avelino/awesome-go#tools section. For example, a vim plugin for Go is likely not written in Go, but it's still an important part of Awesome Go list.
