### ISSUE TITLE
Remove ServeMux

### ISSUE THREAD

**Issue by hallas** [avelino/awesome-go#465]
I have decided to retire my project ServeMux because I couldn't get it to the point where I wanted it API and speed wise. There is no reason to have a lot of frameworks out there that doesn't have a purpose. Please remove it.

Thanks.

**Comment by shurcooL** [comment]
Sure, thanks for the update. Just make a PR.

**Comment by hallas** [comment]
Okay. Your contribution guidelines says to make an issue :-)

**Comment by shurcooL** [comment]
True, that's a little out of date. The README now states:

> If you see a package or project here that is no longer maintained or is not a good fit, please submit a pull request to improve this file. Thank you!

Thanks for catching.
