### ISSUE TITLE
[awesome-go.com]: averageflow/gohooks remove from the list

### ISSUE THREAD

**Issue by dmitrij-onoffapp** [avelino/awesome-go#4698]
> [gohooks](https://github.com/averageflow/gohooks) - GoHooks make it easy to send and consume secured web-hooks from a Go application. Inspired by Spatie's Laravel Webhook Client and Server.

No longer available

**Comment by avelino** [comment]
send PR pls

**Comment by phanirithvij** [comment]
removed in https://github.com/avelino/awesome-go/pull/4708
