### ISSUE TITLE
[awesome-go.com]: Table of Contents Links go to wrong page

### ISSUE THREAD

**Issue by sonashannon** [avelino/awesome-go#4752]
1) Go to https://awesome-go.com/
2) Click on "Bit-packing and Compression"

Result: Browser goes to a separate web page showing an out of date list.

Expected: Browser should scroll down to the Bit-packing and compression area in the same page.

Am I right? I can fix if needed. Why do we have these separate areas? Seems harder to maintain.

**Comment by avelino** [comment]
the behavior should be: go to a category page, showing the updated (not outdated) list

https://github.com/avelino/awesome-go/blob/6d38d787765567517e8b7d8e5f74c9dd8b0c11d3/make_site.go#L112-L133

**Comment by Ashfaq97** [comment]
Hello @avelino 

It looks like the issue has been solved. The link was pointing to the directed place. Could you close the case?

Thanks!
