### ISSUE TITLE
Consider gitter.im over Slack?

### ISSUE THREAD

**Issue by mholt** [avelino/awesome-go#485]
Just a thought - but since Slack has kind of an awkward invite-only system, it has a pretty high barrier to entry. I found [gitter](https://gitter.im) pretty easy to join, since I think it just uses a GitHub login which most everyone here has anyway - no invites needed.

**Comment by shurcooL** [comment]
I have not tried Gitter yet. I think Slack is absolutely excellent, the best I've used, in every way except two: the invite system (worse than IRC) and that it's closed source (worse than IRC & open source server & client).

It seems Gitter is better than Slack on the invite front. If it's as good in every other way, I would consider it seriously.

Thoughts from people who have tried both would be helpful here. Btw, you're talking about the [Gopher slack](http://blog.gopheracademy.com/gophers-slack-community/), right?

**Comment by mholt** [comment]
Yeah, I'm referring to the [link on the readme](https://gophers.slack.com/messages/awesome/) pointing to a fairly idle channel in Slack.

I likewise welcome opinions from anyone who is familiar with both Slack and gitter.

**Comment by bwmarrin** [comment]
Another option is Discord which allows very easy invites and is a rather nice chat environment :)  I was curious where it stood compared to Gitter and found the below issue, which may be useful information here.

https://github.com/reactiflux/volunteers/issues/25

**Comment by avelino** [comment]
+1 gitter

**Comment by matrixik** [comment]
Looks like gitter is in README now. Can be closed?

**Comment by matrixik** [comment]
No response, no objections. Closing.
