### ISSUE TITLE
Fix pull-request-first-comment action

### ISSUE THREAD

**Issue by ravsii** [avelino/awesome-go#4868]
Currently, when a new contributor creates a pull request `pull-request-first-comment` task fails with an error
<img width="407" alt="image" src="https://user-images.githubusercontent.com/5007271/235343478-9a00605c-d6e4-44bf-8821-d34fac64301f.png">

**Comment by avelino** [comment]
this workflow bug https://github.com/avelino/awesome-go/blob/main/.github/workflows/pull-request-first-comment.yaml
