### ISSUE TITLE
Multiple broken hyperlinks

### ISSUE THREAD

**Issue by ndsvw** [avelino/awesome-go#4888]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hello, I found some broken hyperlinks:
- [ ] https://github.com/coreos/etcd/tree/master/raft (file: README.md, status code: 404)
- [ ] https://github.com/if-edge/ekuiper (file: README.md, status code: 404)
- [ ] https://bitbucket.org/vahidi/interpol (file: README.md, status code: 404)
- [ ] https://open.mapquestapi.com/geocoding/ (file: README.md, error: CERT_HAS_EXPIRED)
- [ ] https://rest-layer.io (file: README.md, error: ENOTFOUND)
- [ ] https://github.com/dominikh/go-tools/tree/master/cmd/gosimple (file: README.md, status code: 404)
- [ ] https://github.com/dominikh/go-tools/tree/master/cmd/unused (file: README.md, status code: 404)
- [ ] http://www.capitalgolang.com (file: README.md, status code: 503)
- [ ] https://www.dotgo.eu (file: README.md, error: ECONNRESET)
- [ ] https://gopherchina.org (file: README.md, error: ECONNRESET)
- [ ] https://www.gophercon.in/ (file: README.md, error: ERR_TLS_CERT_ALTNAME_INVALID)
- [x] https://www.meetup.com/golang-users-berlin/ (file: README.md, status code: 404)
- [ ] https://www.meetup.com/GolangKazan/ (file: README.md, status code: 404)
- [ ] https://www.meetup.com/Golang-Peter/ (file: README.md, status code: 404)
- [ ] https://about.sourcegraph.com/handbook/engineering/go_style_guide (file: README.md, status code: 404)

**Comment by phanirithvij** [comment]
Thanks for reporting this!
Need to open a PR with these changes, please do if you have the time, if not I will do it when I can.

- [ ] https://github.com/coreos/etcd/tree/master/raft -> https://github.com/etcd-io/raft
- [ ] https://github.com/if-edge/ekuiper -> https://github.com/lf-edge/ekuiper
- [ ] https://bitbucket.org/vahidi/interpol -> https://github.com/avahidi/interpol/
- [ ] https://open.mapquestapi.com/geocoding ?
- [ ] https://rest-layer.io -> https://github.com/rs/rest-layer
- [ ] https://github.com/dominikh/go-tools/tree/master/cmd/gosimple -> remove
- [ ] https://github.com/dominikh/go-tools/tree/master/cmd/unused -> remove
- [ ] http://www.capitalgolang.com/ -> remove
- [ ] https://www.dotgo.eu -> remove
- [ ] gopherchina.org maybe works in china?
- [ ] https://www.gophercon.in/ -> remove
- [x] https://www.meetup.com/golang-users-berlin/ -> works
- [ ] https://www.meetup.com/GolangKazan/  -> remove
- [ ] https://www.meetup.com/Golang-Peter/ -> remove
- [ ] https://about.sourcegraph.com/handbook/engineering/go_style_guide -> https://docs.sourcegraph.com/dev/background-information/languages/go
