### ISSUE TITLE
bubble table link in error

### ISSUE THREAD

**Issue by jmrenouard** [avelino/awesome-go#4950]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hi,

Link in README.md, bubble table link is https://github.com/Everras/bubble-table
but Github URL is                                     https://github.com/Evertras/bubble-table

Is it a error ?

Best regards,
@jmrenouard

**Comment by avelino** [comment]
@jmrenouard do you send pr correcting?

**Comment by phanirithvij** [comment]
Thanks for reporting, Fixed.
