### ISSUE TITLE
gb build tool

### ISSUE THREAD

**Issue by fzerorubigd** [avelino/awesome-go#497]
this one https://github.com/constabulary/gb is a great tool.
I don't know which section is the best part for this one, so I just open an issue instead of PR.

**Comment by shurcooL** [comment]
gb (/cc @davecheney) is indeed an awesome tool. It's one of a kind, being a replacement for the `go` tool.

I would imagine the best place for it is under the [Tools](https://github.com/avelino/awesome-go#tools) category, but what subcategory is harder to say... Clearly, there's nothing specific for it now. I think [Code Analysis](https://github.com/avelino/awesome-go#code-analysis) category is the best fit, given that it contains other tools related to working with Go code like `goimports`, `lint`, etc. It seems close enough so we don't need to create a separate subcategory. Or we could create "Build Tools" and gb would be the only entry.

What do others think?

**Comment by alaska** [comment]
I don't think Code Analysis is quite the right fit. My vote would be to keep that category for static analysis tools. If you have to create a new category, I'd suggest something like "go project tools", "go build tools" or just put it directly under the tools section.

**Comment by shurcooL** [comment]
> put it directly under the tools section.

I kinda like this. I don't think there will be many viable alternatives to `go` tool, and `gb` can be a standalone entry under Tools header until there's a better category to move it into.

Unless there are any objections? (Disclosure, I know @davecheney personally and I'm familiar with `gb`... But I suppose this applies to many people hehe. :) )
