### ISSUE TITLE
Failed again: https://github.com/avelino/awesome-go/actions/runs/5617685809/job/15222150529?pr=4940

### ISSUE THREAD

**Issue by NahNick** [avelino/awesome-go#5025]
Failed again: https://github.com/avelino/awesome-go/actions/runs/5617685809/job/15222150529?pr=4940

_Originally posted by @carlmjohnson in https://github.com/avelino/awesome-go/issues/4939#issuecomment-1644873830_

**Comment by DHRUV2005MAHESHWARI** [comment]
place all the files in one folder so it should not detect files so it create problem

**Comment by avelino** [comment]
fixed
