### ISSUE TITLE
Add new items.

### ISSUE THREAD

**Issue by moqsien** [avelino/awesome-go#5294]
## DevOps Tools

1. **vmr**([version-manger](https://github.com/gvcgo/version-manager)), a general version manager for multiple sdks.
2. **asciinema**([acast](https://github.com/gvcgo/asciinema)), a cross-platform asciinema(v2) terminal session recorder for MacOS/Linux/Windows.
3. **gobuilder**([gber](https://github.com/gvcgo/gobuilder)), an enhancement for official go build.

**Comment by phanirithvij** [comment]
#5295
