### ISSUE TITLE
Below is a list of projects which have had no code changes in the last 6 months on Github:

### ISSUE THREAD

**Issue by Preacher27** [avelino/awesome-go#5336]
Below is a list of projects which have had no code changes in the last 6 months on Github: 
- [x] [chyrp](https://github.com/chyrp/chyrp) - works as expected
- [x] [myyna](https://github.com/cubettech/myyna) - abandoned
- [x] [scuttle](https://github.com/scronide/scuttle) - some forks https://github.com/makoshark/scuttle/network
- [x] [newebe](https://github.com/gelnior/newebe) - removed but seems to work as expected
- [x] [Baun](https://github.com/BaunCMS/Baun) - apparently maintained
- [x] [OpenEats](https://github.com/qgriffith/OpenEats) 2015, active fork at https://github.com/RyanNoelk/OpenEats
- [x] [daloradius](https://github.com/lirantal/daloradius) - maintained https://github.com/lirantal/daloradius/commits/master
- [x] [CacoCloud](https://github.com/Cacodaimon/CacoCloud) 2015
- [x] [Creaky-Coot](https://github.com/piero-la-lune/Creaky-Coot) - seems to work as expected, simple
- [x] [leselys](https://github.com/socketubs/leselys)  - development restarted
- [x] [lite-reader](https://github.com/cubny/lite-reader) - development restarted
- [x] [Readr](https://github.com/pabloprieto/Readr) - removed in 7d27b53a7a1c19c93dc5d5fb81ecfd00a0cbc425
- [x] [rssminer](https://github.com/shenfeng/rssminer) - removed in 7d27b53a7a1c19c93dc5d5fb81ecfd00a0cbc425
- [x] [ttrss-mobile](https://github.com/mboinet/ttrss-mobile) - works as expected, simple
- [x] [gritttt-rss](https://github.com/nhoening/gritttt-rss) - updated Sep 2016, works as expected, simple
- [x] [Apaxy](https://github.com/AdamWhitcroft/Apaxy) - works as expected, simple
- [x] [MediaCrush](https://github.com/MediaCrush/MediaCrush) -> Remove #1014
- [x] [FileTea](https://github.com/elima/FileTea) -> Remove #1014
- [x] [sharefest](https://github.com/peer5/sharefest) -> Remove #1014
- [x] [20euros](https://github.com/jatekos101/20euros) -> simple, works as expected
- [x] [Cubiks-2048](https://github.com/Kshitij-Banerjee/Cubiks-2048) -> simple, works as expected
- [x] [mindmaps](https://github.com/drichard/mindmaps) -> https://github.com/nielinjie/mindmaps
- [x] [jotter](https://github.com/yosko/jotter) -> Remove #1014
- [x] [minimalist-web-notepad](https://github.com/pereorga/minimalist-web-notepad) - works as expected, simple
- [x] [notes](https://github.com/SSilence/notes) -> maintained, simple enough, seems to work as expected
- [x] [cryptonote](https://github.com/alainmeier/cryptonote) -> maintained, simple enough, seems to work as expected
- [x] [haste-server](https://github.com/seejohnrun/haste-server) 
- [x] [pastedown](https://github.com/cespare/pastedown) -> Remove #1014
- [x] [Reportr/dashboard](https://github.com/Reportr/dashboard) -> Remove #1014
- [x] [gallery3](https://github.com/gallery/gallery3) - unmaintained http://galleryproject.org/
- [x] [phog](https://github.com/hillman/phog) removed in d39b29ba21b9c5c0832d1c6836de4016911b5257
- [x] [PhotoLight](https://github.com/thibaud-rohmer/PhotoLight), simple codebase, works as expected, no major issues
- [x] [pygmyfoto](https://github.com/dmpop/pygmyfoto) removed d39b29ba21b9c5c0832d1c6836de4016911b5257
- [ ] [Shot.io](https://github.com/AliasIO/Shot.io) abandoned 2014 -> Remove
- [x] [Kyela](https://github.com/abienvenu/Kyela) maintained 2017
- [x] [OpenSondage](https://github.com/leblanc-simon/OpenSondage) maintained in fork
- [ ] [scotty](https://github.com/SSilence/scotty) unmaintained, complex code (java), security component -> Remove
- [x] [OranjeProxy](https://github.com/AmauryCarrade/OranjeProxy) seems to work in most cases, simple codebase (704 lines of PHP)
- [ ] [readityourself](https://github.com/memiks/readityourself) - unmaintained, doesn't work anymore, remove
- [x] [pairjam](https://github.com/neerajwahi/pairjam) unmaintained
- [ ] [docstore](https://github.com/haldean/docstore) (see below), seems to work as expected but was removed in 0e7238a59b2074640f9bf5907e05c66f95f5fa36. Now under BSD license -> re-add it
- [x] [markdown-tree](https://github.com/mil/markdown-tree) - works as expected, simple
- [ ] [bulldog](https://github.com/infews/bulldog) 2017-04-04 see below, waiting for maintainer reply
- [x] [tasks.php](https://github.com/RaymiiOrg/tasks.php) simple code, low maintenance, no major problems https://github.com/Kickball/awesome-selfhosted/pull/969
- [x] [tinyissue](https://github.com/mikelbring/tinyissue) unmaintained, removed
- [x] [Bumpy-Booby](https://github.com/piero-la-lune/Bumpy-Booby) - works as expected, simple
- [ ] [gaskit](https://github.com/bkeepers/gaskit) maintainer reply below: unmaintained, unknown working state -> Remove
- [x] [blazekiss](https://github.com/ldleman/blazekiss) 1000 lines of PHP, seems to work as expected -> Keep it in the list
- [x] [commonplace](https://github.com/fredoliveira/commonplace) 280 lines of ruby, dependencies can be updated through bundle install
- [ ] [gruik](https://github.com/grena/gruik) README.md states abandoned project -> Remove
- [x] [olelo](https://github.com/minad/olelo), maintainer active, seems to work as expected -> Keep
- [ ] [Wikitten](https://github.com/victorstanciu/Wikitten), unmaintained, security-related bugs -> Remove

_Originally posted by @Kickball in https://github.com/awesome-selfhosted/awesome-selfhosted/issues/381_

**Comment by phanirithvij** [comment]
Please stop spamming.
