### ISSUE TITLE
Investigate `Ineligible` PRs

### ISSUE THREAD

**Issue by yassinebenaid** [avelino/awesome-go#5368]
Some PRs are ineligible and need to be closed. Ineligible PRs are the ones that add ineligible project to the list, and/or have unresolved discussions.

I'll keep listing them here every time I encounter them.

**Comment by yassinebenaid** [comment]
- #4469 : 
    - unresolved discussion
    - unstable version
    - last update more than a year
    - have unresolved issues since 2022.
    - CI is missing

**Comment by yassinebenaid** [comment]
- #4472 : 
    - This PR is trying to add the `net` package from the go standard library
    - Labeled as `stale`

**Comment by yassinebenaid** [comment]
- #4471 : 
    - This PR adds [golang.org/x/net/context/ctxhttp](https://pkg.go.dev/golang.org/x/net/context/ctxhttp)
    - Labeled as `stale`

**Comment by yassinebenaid** [comment]
- #4487 :
    - Project is no longer maintained (last update 2 years ago)
    - Missing stable version

**Comment by yassinebenaid** [comment]
- #4490 : 
    - No longer maintained (Last update 2 years ago)
    - Missing stable version

**Comment by yassinebenaid** [comment]
- #4525  : 
    - last update 4 years ago
    - unresolved open issues, one of which is a  bug report https://github.com/blang/semver/issues/75.

**Comment by yassinebenaid** [comment]
@phanirithvij please consider taking a look at these PRs when you're free.

**Comment by phanirithvij** [comment]
Thanks! if you're interested in becoming a maintainer ping avelino, he can give you access.
Closing this, re open if needed.

**Comment by yassinebenaid** [comment]
@avelino ping

**Comment by avelino** [comment]
https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#how-to-become-a-contributor

@yassinebenaid did you get to read the contribution document?
There we explain how to become a contributor, just contribute as a maintainer by reviewing PRs and aiming for awesome-go to be more automated with code.

Looking at your contribution to this issue, I think it's important to have you on the maintainer team - I've already added you as a maintainer.

Welcome aboard! Please help us review the open PRs.
