### ISSUE TITLE
Should We add new category : `Reflection`

### ISSUE THREAD

**Issue by yassinebenaid** [avelino/awesome-go#5379]
Should we add a new category called `Reflection` under which all reflection related projects will be listed?.

This is related to this: https://github.com/avelino/awesome-go/pull/5355#issuecomment-2252253272

**Comment by phanirithvij** [comment]
I'll work on this in a pr and request for review.

**Comment by mooh60** [comment]
Hi evfennn

**Comment by Arnav-2004** [comment]
@yassinebenaid and @phanirithvij I noticed that this issue has been inactive for a while. I'd be happy to work on it if it's still relevant.

**Comment by phanirithvij** [comment]
sure

**Comment by Arnav-2004** [comment]
> sure

@phanirithvij I have created a PR for the same.
