### ISSUE TITLE
Typo in Blockchain section: 'Lighting Network' should be 'Lightning Network'

### ISSUE THREAD

**Issue by 0xvish** [avelino/awesome-go#5511]
### Search first

- [X] I searched and no similar issues were found

### Description
In the [Blockchain section](https://github.com/avelino/awesome-go#blockchain) of the `README.md`, the word "Lightning" is misspelled as "Lighting" for the `[lnd](https://github.com/lightningnetwork/lnd)` entry.

---

### Expected Behavior
> [lnd](https://github.com/lightningnetwork/lnd) - Lightning Network implementation in Go.

---

### Actual Behavior
> [lnd](https://github.com/lightningnetwork/lnd) - Lighting Network implementation in Go.

---

### Suggested Fix
Fix the typo to:
> [lnd](https://github.com/lightningnetwork/lnd) - Lightning Network implementation in Go.

![image](https://github.com/user-attachments/assets/63a1cfb6-7a88-4ee2-8259-cffe686d6d02)

**Comment by phanirithvij** [comment]
Thanks for noticing it

**Comment by flossybloom67** [comment]
> ### Search first
> 
> - [X] I searched and no similar issues were found
> 
> ### What Happened?
> 
> ### Description
> In the [Blockchain section](https://github.com/avelino/awesome-go#blockchain) of the `README.md`, the word "Lightning" is misspelled as "Lighting" for the `[lnd](https://github.com/lightningnetwork/lnd)` entry.
> 
> ---
> 
> ### Expected Behavior
> > [lnd](https://github.com/lightningnetwork/lnd) - Lightning Network implementation in Go.
> 
> ---
> 
> ### Actual Behavior
> > [lnd](https://github.com/lightningnetwork/lnd) - Lighting Network implementation in Go.
> 
> ---
> 
> ### Suggested Fix
> Fix the typo to:
> > [lnd](https://github.com/lightningnetwork/lnd) - Lightning Network implementation in Go.
> 
> 
> ![image](https://github.com/user-attachments/assets/63a1cfb6-7a88-4ee2-8259-cffe686d6d02)
>
