### ISSUE TITLE
"Web frameworks" category

### ISSUE THREAD

**Issue by alkchr** [avelino/awesome-go#585]
To the question of categories, there is something strange with **Web frameworks**. It is [described](https://github.com/avelino/awesome-go#web-frameworks) as "Full stack web frameworks". But most elements there are neither frameworks nor fullstack. There should be at least 3 subcategories:
1. Routers (aka mux): bone, httprouter, mux, pat, etc.
2. Micro-frameworks: those which provide only middleware + mux.
3. Full-stack frameworks: all-in-one solutions.
It is possible to go even further, and rename "Web frameworks" into "Web-development". Then it would be possible to create a "Client-side" category for projects such as gopherjs, minify, etc. and "Tools" for things like #422 (as for _at least 3 items_ rule: I'm sure more than 3 tools in Go for web-development exist).

**Comment by wetgi** [comment]
+1 for Categories

**Comment by romatthe** [comment]
I actually wanted to file an issue for this as well. The **Web Frameworks** category makes very little sense. Almost 90% of these projects are libraries for building services. Which is great, but "Full Stack" usually implies opinionated techniques such as MVC and ORM, tools for scaffolding, and some sort of solution for the client side (templating, etc.).

I suggest one of the following:
1. Change the description from "Full Stack" to something else.
2. Add additional categories like @alkchr suggested
