### ISSUE TITLE
dead goose

### ISSUE THREAD

**Issue by bwiggs** [avelino/awesome-go#607]
Looks like the goose database migration project is no longer actively maintained.

https://bitbucket.org/liamstask/goose/issues/58/is-this-project-dead

**Comment by matrixik** [comment]
Thank you for information, sorry it took so long.

Hello @phemmer and @zabawaba99
I replaced bitbucked link to `goose` with your fork in https://github.com/avelino/awesome-go/commit/1891e0fe6b5411717bc1c4e7adee9cb5a2f985d7. 
Thank you for your continuous support (https://github.com/CloudCom/goose/issues/20).

When you have some time you could maybe check some `golint` warnings and coverage for package:
https://goreportcard.com/report/github.com/CloudCom/goose
https://gocover.io/github.com/CloudCom/goose/lib/goose/

**Comment by zabawaba99** [comment]
Hi @matrixik unfortunately, @phemmer and I no longer have access to CloudCom/goose as we were removed form the organization. We would be happy to maintain this project and move it over to [steinbacher/goose](https://github.com/steinbacher/goose). Also, the repository is under an organization so that we could add other contributors if anyone is interested in helping maintain the project.

**Comment by matrixik** [comment]
So if you are moving again you could implement breaking changes now like https://github.com/CloudCom/goose/issues/3 without too much problems for old code? And what will happen now to CloudCom/goose ?

**Comment by zabawaba99** [comment]
I cloned all the issues we had in CloudCom to steinbacher. I can probably tackle some of them this weekend.

As far as what will happen to CloudCom/goose, I'm not sure. I haven't seen any pulse on the project since we touched it so I don't know if someone is working on it or if it's been abandoned.

**Comment by zabawaba99** [comment]
@matrixik Heads up on CloudCom/goose#3 (which maps to https://github.com/steinbacher/goose/issues/6). It was completed and merged into master. Was going to continue working on the code to bring up test coverage.

**Comment by matrixik** [comment]
Thank you for maintaining this project. Link changed.
