### ISSUE TITLE
Bring existing list into conformity with contribution guidelines

### ISSUE THREAD

**Issue by mholt** [avelino/awesome-go#66]
I drafted up a [contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md) page just to get something started. (Feedback is welcome.)

If it looks mostly good, we should start updating the list as it stands to help it to conform with the quality standards. This mainly means:

- [x] Sort items alphabetically (should categories be alphabetical, too?)
- [ ] Remove items that lack documentation or are not maintained
- [x] Decide on whether to keep Go *software* (see [this issue comment](https://github.com/avelino/awesome-go/issues/51#issuecomment-48143147))
- [x] Move software into its own category or file
- [ ] Mark packages as experimental or transitory as necessary
- [x] Links should go to repository pages, not marketing/frontage pages (unless the pages contain more useful documentation and links back to the actual repository)

I'll have some time to work on this but the list got huge really fast so help would be nice.

**Comment by shurcooL** [comment]
Is this still an actionable issue? The last update was made more than 6 months ago.

If so, what remains to be done before it can be closed?

**Comment by mholt** [comment]
Eh, good point. I don't know of any problems anymore with the existing list -- but if we or anyone finds an issue, we can deal with it then.
