### ISSUE TITLE
Automate the acceptance of high quality repos 

### ISSUE THREAD

**Issue by levigross** [avelino/awesome-go#683]
Hi,

I prepose that you should consider automating the merging of certain entries. The hard part is using the proper metrics.

I would like to start the conversation by suggesting the following metrics. 
- Github stars
- Test coverage
- The output of http://goreportcard.com/ (which checks `go vet`, `go lint`, and `go fmt`)

**Comment by joeybloggs** [comment]
Just my 2 cents,

* stars should not be taken into account for 2 reasons:
  * just because it has a bunch of stars does not mean it's any good.( just being realistic)
  * I've submitted pull requests and had packages added with very few stars if any, the whole point was to get some exposure, which stars may be a by-product

*  Test coverage for sure ,but what percentage, may have to be as low as 50-60% as sometimes some things cannot be faked reliably I.e. read failure from file on disk.

* Goreportcard is a great idea, the only thing that would concern me is the cyclomatic checking that site does, I don't know at what complexity to it starts showing issues, but I have a project where it shows issues where there are none.

**Comment by levigross** [comment]
@joeybloggs 

I agree with your sentiments on Github stars. My opinion is based on the following two points:

1. Sometimes you have a product that is popular but doesn't have great test coverage: e.g Docker. 
1. Popular packages benefit from the community (and therefore over time and with the right management, their code quality gets really good)

As for test coverage, I am not suggesting that we only accept projects with 90% code coverage, but I do think it is important to assess a project based on its code coverage. The exact percentage should be determined based the list's existing coverage.

Additionally, I would like to suggest another metric we can use, longest unanswered Github issue. That will help us understand if the project is alive or not. 

Finally, I feel that it is important to remember, we want to *automate* the acceptance of items. We should validate whatever metrics we use by feeding the current list into the "automator" and seeing what comes out.

**Comment by shurcooL** [comment]
I agree that this is an effort worth investing into, because it seems the current amount of inbound Pull Request is higher than the capacity of the contributors to accept it. There are many, many PRs that go unreviewed for weeks, if not months, which is a problem.

**Comment by jgoodall** [comment]
Also throwing in my 2 cents... This site is described as "A curated list of awesome Go frameworks, libraries and software". _Curated_ implies that someone is actually reviewing the packages that get added to the list. If you start talking about automation, and there is no review, the _curated_ probably needs to be dropped. 

I was surprised to find so many packages here that seem to have so little activity (very few stars, forks, PRs, issues) and no packages reported on godocs as using it (e.g. [go-playground/pool](https://godoc.org/gopkg.in/go-playground/pool.v1)). My expectation was that the list was of packages that knowledgeable go programmers used. Is it more like anyone can submit a PR and someone just clicks accept? That is totally fine and not being critical, but maybe change the description...

**Comment by alaska** [comment]
@jgoodall, I actually started a tool to go through all repos and mark any that looked dead for further review.  At such time a package could either be marked as stable (in which case it would stop alerting until changed), or evaluated and either removed or excepted as the case warranted.  Might be time to resurrect the project.

**Comment by joeybloggs** [comment]
Seems like I'm being called out :wink: Just a quick point @jgoodall I don't think that godocs properly reports usage, point in case see here https://godoc.org/gopkg.in/go-playground/validator.v8?importers, lists 2 packages even it's used in many more and clone many thousands of times each week.

**Comment by jgoodall** [comment]
@alaska - that definitely sounds like a useful utility!

**Comment by jgoodall** [comment]
@joeybloggs - sorry, not calling anyone out. I came to this list because of the 'curated' part, but maybe others are just looking for a big list of packages. Is there another way to determine what packages are actually being used? http://go-search.org/? Or does godoc skew numbers when relying on gopkg.in? Of is that particular example maybe not a good one because of so multiple versions?

**Comment by edigu** [comment]
+1 for the "curated part"

**Comment by joeybloggs** [comment]
No worries @jgoodall , I was jk, I honestly don't know about gopkg.in skewing or not but it seems strange that it's reporting 2, but not anymore; perhaps only other packages that have been initialized/have godocs are reported?

**Comment by shurcooL** [comment]
Perhaps, in order to enable the curated part, this issue can be flipped around as "automate closing PRs that add low quality repos". If the volume is decreased, it's easier for the few contributors to review and accept high quality packages.

It's still hard because there are many, many packages.

**Comment by avelino** [comment]
start implementation https://github.com/avelino/awesome-go/blob/checkGoreportcard/repo_test.go#L109


is extremely slow check all, if anyone has any idea how to improve

**Comment by levigross** [comment]
If I understand the code correctly, on every pull request runs this test across all of the entries (effectively launching a denial of service attack against `goreportcard.com`). I would ask permission if we can use the service and have it only test the repos added within the pull request.

**Comment by avelino** [comment]
Ideally, we'd be turning these check location!

**Comment by avelino** [comment]
goreportcard source: https://github.com/gojp/goreportcard/blob/master/handlers/checks.go

**Comment by shawnps** [comment]
> If I understand the code correctly, on every pull request runs this test across all of the entries (effectively launching a denial of service attack against goreportcard.com). I would ask permission if we can use the service and have it only test the repos added within the pull request.

This is probably what happened earlier when @avelino said it was slow. Go Report Card runs on a single, cheap cloud server and ran out of memory. It should be back to normal now, but I'll think about a way to do some rate-limiting, or something, to make Go Report Card better if it's going to be used in this way. For the record I'm totally fine with checking repos against it (there is another tool that uses it in a similar way), but I agree with @levigross in that it'd be better if it's not a massive amount of requests all at once and rather a request for a single repo when a PR comes in.

**Comment by avelino** [comment]
About curating, when you have 100% coverage (https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) of text and still have some of the cases that will come out of default, i.e. I think the curators will decrease too (is what we need), but in some cases it will be necessary.
