### ISSUE TITLE
blas

### ISSUE THREAD

**Issue by konqoro** [avelino/awesome-go#731]
https://github.com/ziutek/blas doesn't seem actively maintened. You could replace it with https://github.com/gonum/blas

**Comment by matrixik** [comment]
Hi, thank you for info.
Does https://github.com/gonum/blas is similarity optimized like https://github.com/ziutek/blas ?

Hello @ziutek could you give us some status of https://github.com/ziutek/blas ?

**Comment by ziutek** [comment]
blas is small and simple library that supports only easy to implement a subset of BLAS. It is optimized only for AMD64.

I use it in my one project. It seems that some people use it too. It compiles. All tests pass. All benchmarks works.

**Comment by matrixik** [comment]
Thank you for reply.
I think both packages could be listed in awesome-go.
But gonum/blas is lacking docs in code: https://goreportcard.com/report/github.com/gonum/blas#golint

**Comment by btracey** [comment]
The intent is for users to use blas/blas64, which is well documented
https://godoc.org/github.com/gonum/blas/blas64

The native Go implementation is also well documented 
https://godoc.org/github.com/gonum/blas/native

Most of the items lacking in documentation are either auto-generated functions from C (implementation.Zher2, for example), or are functions in the testing package.

**Comment by avelino** [comment]
send pull request, if all OK will be done merge
