### ISSUE TITLE
please add star and fork before every project to show the popularity 

### ISSUE THREAD

**Issue by Arkingtse** [avelino/awesome-go#834]
It's convenient to know which is popular at first glance
add the create time will be event better

there is no need to be dynamic, just update it everytime you gennerate it

**Comment by Arkingtse** [comment]
like this
1316/11256    awesome-go

**Comment by kamilsk** [comment]
Hi! Open http://awesome-go.com/ and run https://gist.github.com/kamilsk/128d6be5db2e86c0dd95 from your console (don't forget to replace `<put your token>` by your [personal access tokens](https://github.com/settings/tokens)). Enjoy!

**Comment by dgryski** [comment]
Stars and forks are more correlated with publicity than quality: http://www.cockroachlabs.com/blog/what-can-we-learn-from-our-github-stars/

**Comment by matrixik** [comment]
We do not generate our list at any moment.
http://awesome-go.com/ data is pulled straight from github: https://github.com/avelino/awesome-go/blob/gh-pages/assets/awesome-go.js

Thank you for idea but what @kamilsk provided should be sufficient, adding it to repo would create many unnecessary commits. It would need to be automated and the more links we would have the more time generation would take every time and at some point we would be hitting github API rate limiting.
Also what @dgryski linked to have a point.

Thank you all for contribution. Closing.

**Comment by cctse** [comment]
@kamilsk @dgryski thanks.    @matrixik sorry for this,  I wasn't aware of the problem that it need to generate every time the star changes

**Comment by kirillDanshin** [comment]
@cctse maybe later I'll write a new version of awesome-go.com in go, and it will be track star changes, forks and last push date. but I don't think I can do it this month.

**Comment by cctse** [comment]
@kirillDanshin never mind,  it's just a minor recommendation
