### ISSUE TITLE
PULL_REQUEST_TEMPLATE file

### ISSUE THREAD

**Issue by matrixik** [avelino/awesome-go#855]
I would like to add file **PULL_REQUEST_TEMPLATE** to repo:
```
Please check if what you want to add to `awesome-go` list meets 
[quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) 
before sending pull request. Thanks!

Link to https://goreportcard.com/: <>

Link to https://gocover.io/: <>
```
Objections, comments?
@avelino  @shurcooL

**Comment by shurcooL** [comment]
No objections from me, that looks good.

Minor, but maybe make the first paragraph into a single sentence. Right now, it would render oddly across 3 lines:

> Please check if what you want to add to `awesome-go` list meets 
[quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) 
before sending pull request. Thanks!

**Comment by matrixik** [comment]
Thank you for comment. When I tried it yesterday it was rendered in one line, it needed empty line between lines I wanted in separate lines (nice sentence ;) ).

**Comment by matrixik** [comment]
I also thinking about adding as last line something like:
`If package have low scores inform maintainers or you could help them with PR.`
Or maybe you could propose some better sounding advice.

**Comment by kirillDanshin** [comment]
What do you think about adding something like this checklist and note below?

---

Note, that new categories can be added only when there are 3 packages or more.

Make shure that you've checked the boxes below before you submit PR:
- [ ] I have added my package in alphabetical order
- [ ] I know that this package was not listed before
- [ ] I have added godoc link
- [ ] I have added gocover.io link
- [ ] I have added goreportcard link
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome :+1:

---

**Comment by avelino** [comment]
+1

**Comment by kirillDanshin** [comment]
Please, review my PR (#890).
