### ISSUE TITLE
Add DoNotMerge label

### ISSUE THREAD

**Issue by kirillDanshin** [avelino/awesome-go#891]
Sometimes author don't want to merge PR yet, for example see #873.
Maybe we can create a DoNotMerge label?

@avelino @matrixik @shurcooL

**Comment by kamilsk** [comment]
why not "wip"/"status:wip" (work in progress) label?

**Comment by kirillDanshin** [comment]
@kamilsk yep, it's fine too :)

**Comment by avelino** [comment]
+1
