### ISSUE TITLE
How about labels with categories?

### ISSUE THREAD

**Issue by kamilsk** [avelino/awesome-go#896]
Like this https://github.com/ziadoz/awesome-php/labels

**Comment by kirillDanshin** [comment]
Just don't see when we need this.
Any idea how it can help in our case?

**Comment by kamilsk** [comment]
quick filtering of pull requests for example. if I'm interested in one category, I will actively look for it

**Comment by kirillDanshin** [comment]
ok, I see.
no objection from me.
