### ISSUE TITLE
Dependency Injection frameworks?

### ISSUE THREAD

**Issue by arvenil** [avelino/awesome-go#902]
Hi,

The `awesome-go` library list is impressive however I couldn't find any DI frameworks... but maybe I simply wasn't able to find them on the list? :)

For sure two I can't find are:
https://github.com/facebookgo/inject
https://github.com/karlkfi/inject

... and I was hoping to find others, anybody knows about anymore worth trying?

**Comment by avelino** [comment]
karlkfi/inject not best quality

**Comment by arvenil** [comment]
@avelino  Why you say karlkfi/inject is not best quality? I've actually ended up using github.com/karlkfi/inject in project rather than facebookgo/inject. And actually they both approach the problem differently - karlkfi/inject solution is more appealing to me. To me looks like facebookgo/inject has more stars only because there is *facebook* in the name

**Comment by avelino** [comment]
test not found (not a)
