### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by AlekSi** [avelino/awesome-go#922]
https://github.com/golang/exp/tree/master/shiny

**Comment by kirillDanshin** [comment]
Please, add links and submit it as pull request. Thanks!

**Comment by AlekSi** [comment]
That's more or less "drive-by" issue. I can't do it now. If no-one will do it soon, I will do it (later).

**Comment by kirillDanshin** [comment]
@AlekSi ok, I'll review it and if it's ok I'll push it

**Comment by kamilsk** [comment]
@kirillDanshin, it is part of experimental packages. why should it be here?

**Comment by shurcooL** [comment]
Shiny is in theory unfinished and experimental, which should be noted, but it is quite complete and very interesting. It's an actively researched and developed spiritual successor to GXUI, one of the best UI packages in pure Go, and it's likely a contender for top spot for Go UI packages. I think it's definitely worth listing.

**Comment by kamilsk** [comment]
I'm a bit about something else. Experimental packages are on the official golang site https://golang.org/pkg/#other and shiny is part of this list.

I thought that the main target of awesome-go list is to help users find packages which not presented in official site/docs.

Little example: nobody adds links of [yaml](http://php.net/manual/en/book.yaml.php) to http://php.libhunt.com because they already presented in official docs (but not a part of php core).

**Comment by solojavier** [comment]
I don't think this qualifies to be here since it doesn't have the following:

* Generally useful to the wider community of Go programmers
* Stable or progressing toward stable
* Thoroughly documented (README, godoc comments, etc.)

**Comment by johnliz4ever** [comment]
#https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F717080514931376129%2Fhfhzm06Q.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Fgoogleplay&docid=ZOMyK2156PnSSM&tbnid=Qc0KJ8jRd_j1wM%3A&w=512&h=512&bih=520&biw=360&ved=0ahUKEwj7i6uJ7-jOAhUDKiYKHY-VB70QMwhHKAAwAA&iact=mrc&uact=8https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F717080514931376129%2Fhfhzm06Q.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Fgoogleplay&docid=ZOMyK2156PnSSM&tbnid=Qc0KJ8jRd_j1wM%3A&w=512&h=512&bih=520&biw=360&ved=0ahUKEwj7i6uJ7-jOAhUDKiYKHY-VB70QMwhHKAAwAA&iact=mrc&uact=8https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F717080514931376129%2Fhfhzm06Q.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Fgoogleplay&docid=ZOMyK2156PnSSM&tbnid=Qc0KJ8jRd_j1wM%3A&w=512&h=512&bih=520&biw=360&ved=0ahUKEwj7i6uJ7-jOAhUDKiYKHY-VB70QMwhHKAAwAA&iact=mrc&uact=8https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F717080514931376129%2Fhfhzm06Q.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Fgoogleplay&docid=ZOMyK2156PnSSM&tbnid=Qc0KJ8jRd_j1wM%3A&w=512&h=512&bih=520&biw=360&ved=0ahUKEwj7i6uJ7-jOAhUDKiYKHY-VB70QMwhHKAAwAA&iact=mrc&uact=8https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F717080514931376129%2Fhfhzm06Q.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Fgoogleplay&docid=ZOMyK2156PnSSM&tbnid=Qc0KJ8jRd_j1wM%3A&w=512&h=512&bih=520&biw=360&ved=0ahUKEwj7i6uJ7-jOAhUDKiYKHY-VB70QMwhHKAAwAA&iact=mrc&uact=8

**Comment by kirillDanshin** [comment]
@johnliz4ever are you sure that link is right?
