### ISSUE TITLE
Gowut - which category?

### ISSUE THREAD

**Issue by icza** [avelino/awesome-go#946]
I have created a Go Web UI Toolkit:

https://github.com/icza/gowut

It is in a stable and feature-rich state, can be used in production, richly documented and there are many examples, as well as a [live demo](https://gowut-demo.appspot.com/show).

I have some trouble choosing a category for it: it is a GUI framework ("GUI" category) but it is implemented as a web server and clients are browsers ("Web Frameworks" category).

What makes the decision ambiguous is that with Gowut you can build single-page web UI using pure Go and nothing else (UI is assembled with Go, state stored in Go, client code is generated by the Go code automatically, transparently), the HTML/CSS/JS layer is "hidden" by Gowut (but is accessible for those who want to go down to that level). This suggests me that it should be put in the "GUI" category, but it works like a web server - web client.

**Comment by kirillDanshin** [comment]
@icza I think it should be in "Web Frameworks" category

**Comment by gnewton** [comment]
So I _think_ you just need to open a branch, add gowut to the "Web Frameworks" section and make a pull request?

**Comment by icza** [comment]
Already did that. Pull request was denied due to lack of comprehensive tests. Will come back to that later. Closing this.

**Comment by gnewton** [comment]
Ah. I see. Apologies for wasting your time.
 I was not aware they demanded comprehensive tests to be on the list....
